// packages/platforms/vue2/src/core4vue/widgets/GraphLoading.vue
<template>
    <div
            class="rg-graph-loading"
            :class="{'rg-graph-loading-hide': !options.graphLoading}"
            @click="clickGraphMask"
    >
        <div v-if="options.graphLoadingText" class="rg-graph-loading-message">
            <RGIcons icon-name="icon-lianjiezhong" class-name="rg-graph-loading-icon"/>
            {{ options.graphLoadingText || 'Loading...' }}
        </div>
    </div>
</template>

<script lang="ts">
import RGIcons from "./RGIcons";

export default {
    name: 'GraphLoading',
    components: {RGIcons},
    data() {
        return {};
    },
    inject: ['graphStore'],
    computed: {
        graphInstance() {
            return this.graphStore.graphInstance;
        },
        options() {
            return this.graphStore.options;
        }
    },
    methods: {
        clickGraphMask(e) {
            this.graphInstance.clearLoading();
        }
    }
};
</script>

// packages/platforms/react/src/relation-graph/src/core4react/widgets/GraphLoading.tsx
import React from 'react';
import RGIcons from "./RGIcons";
import {useGraphInstance} from "../../hooks/useGraphInstance";
import {useGraphStore} from "../../hooks/useGraphStore";

const GraphLoading: React.FC = () => {
  const graphInstance = useGraphInstance();
  const {options} = useGraphStore();
  const clickGraphMask = (e) => {
    graphInstance.clearLoading();
  }
  return (
    <>
    {
      options && <div
    className={`rg-graph-loading ${!options.graphLoading ? 'rg-graph-loading-hide' : ''}`}
    onClick={(e) => {clickGraphMask(e);}}
  >
    <div className="rg-graph-loading-message">
      <RGIcons iconName="icon-lianjiezhong" className="rg-graph-loading-icon" />
        {options.graphLoadingText || 'Loading...'}
    </div>
  </div>
}
    </>
  );
};

export default GraphLoading;
