// packages/platforms/svelte/src/core4svelte/widgets/GraphBackground.svelte
<script lang="ts">
    import { onMount, onDestroy } from 'svelte';
    import { useGraphInstance } from '../../hooks/useGraphInstance';
    import {useGraphStore} from "../../hooks/useGraphStore";

    export let forImage = true;
    export let forDisplay = true;

    let backgroundRef: HTMLElement;

    const graphInstance = useGraphInstance();
    const {optionsStore} = useGraphStore();
    $: options = $optionsStore;

    onMount(() => {
        if (backgroundRef) {
            graphInstance.setBackgroundDom(backgroundRef, forImage, forDisplay);
        }
    });

    onDestroy(() => {
        graphInstance.setBackgroundDom(null, forImage, forDisplay);
    });
</script>

<div
        bind:this={backgroundRef}
        class="rg-background"
        style:display={forDisplay !== false ? '' : 'none'}
>
    <slot />
</div>

// packages/platforms/react/src/relation-graph/src/core4react/widgets/GraphBackground.tsx
import React, {PropsWithChildren, useRef, useEffect} from 'react';
import {RGBackgroundProps} from "../../../../../../../types";
import {useGraphInstance} from "../../hooks/useGraphInstance";

const GraphBackground:React.FC<PropsWithChildren<RGBackgroundProps>> = ({ children, forDisplay, forImage }) => {
  const graphInstance = useGraphInstance();
  const $backgroundRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    graphInstance.setBackgroundDom($backgroundRef.current, forDisplay, forImage);
    return () => {
      graphInstance.setBackgroundDom(null, forDisplay, forImage);
    };
  }, []);
  return (
    <div
      className={`rg-background`}
      ref={$backgroundRef}
    >
      {children}
    </div>
  );
};

export default GraphBackground;
