// packages/platforms/vue3/src/relation-graph/src/core4vue3/widgets/GraphXsToolBar.vue
<script lang="ts" setup>
import {computed} from 'vue'
import RGIcons from "./RGIcons.vue";
import {useGraphInstance} from "../../hooks/useGraphInstance";

const props = defineProps<{
    direction?: 'v' | 'h',
    positionH?: 'left' | 'center' | 'right',
    positionV?: 'top' | 'center' | 'bottom',
}>(); // RGToolBarProps
const graphInstance = useGraphInstance();
const options = computed(() => graphInstance.dataStores.optionsRef.value);
const toggleAutoLayout = () => {
    graphInstance.toggleAutoLayout();
}
const zoomToFit = async () => {
    graphInstance.enableCanvasAnimation();
    graphInstance.setZoom(100);
    graphInstance.moveToCenter();
    graphInstance.zoomToFit();
    setTimeout(() => {
        graphInstance.disableCanvasAnimation();
    }, 300);
}
const doZoom = async (value: number) => {
    graphInstance.zoom(value);
}
const fullscreen = async () => {
    graphInstance.fullscreen();
}
</script>
<template>
    <div
            class="rg-toolbar rg-xs-toolbar"
            :class="['rg-toolbar-h-' + (positionH||options.toolBarPositionH || 'left'), 'rg-toolbar-v-' + (positionV||options.toolBarPositionV||'bottom'), 'rg-toolbar-' + (direction||options.toolBarDirection||'h')]"
    >
        <div title="Full Screen" class="rg-mb-button" style="margin-top: 0px;" @click="fullscreen">
            <RGIcons icon-name="icon-quanping"/>
        </div>
        <div class="rg-mb-button" @click="doZoom(20)">
            <RGIcons icon-name="icon-fangda"/>
        </div>
        <div class="rg-current-zoom" @click="zoomToFit">{{ Math.round(options.canvasZoom) }}%</div>
        <div class="rg-mb-button" style="margin-top:0px;" @click="doZoom(-20)">
            <RGIcons icon-name="icon-suoxiao"/>
        </div>
        <div v-if="options.layout.supportAutoLayout"
             :title="options.layout.autoLayouting?'Stop Force Layout':'Start Force Layout'"
             :class="{'rg-mb-button-on':options.layout.autoLayouting}" class="rg-mb-button" @click="toggleAutoLayout">
            <RGIcons v-if="!options.layout.autoLayouting" icon-name="icon-zidong"/>
            <RGIcons v-else icon-name="icon-lianjiezhong" class-name="rg-loading-icon"/>
        </div>
        <slot/>
        <div style="clear: both;"></div>
    </div>
</template>

// packages/platforms/react/src/relation-graph/src/core4react/widgets/GraphXsToolBar.tsx
import React, {PropsWithChildren, useEffect} from 'react';
import {RGToolBarProps} from '../../../../../../../types';
import RGIcons from "./RGIcons";
import {useAutoUpdateView, useGraphInstance} from "../../hooks/useGraphInstance";
import {useGraphStore} from "../../hooks/useGraphStore"; // You need to create this context similar to Vue's inject

const GraphXsToolBar: React.FC<PropsWithChildren<RGToolBarProps>> = ({
                                                      direction = '',
                                                      positionH = '',
                                                      positionV = '',
                                                      children
                                                  }) => {
    const graphInstance = useGraphInstance();
    useAutoUpdateView();
    const {options} = useGraphStore();

    const toggleAutoLayout = () => {
        graphInstance?.toggleAutoLayout();
    };

    const zoomToFit = async () => {
        if (graphInstance) {
            graphInstance.enableCanvasAnimation();
            graphInstance.setZoom(100);
            graphInstance.moveToCenter();
            graphInstance.zoomToFit();
            setTimeout(() => {
                graphInstance.disableCanvasAnimation();
            }, 300);
        }
    };

    const doZoom = async (value: number) => {
        await graphInstance?.zoom(value);
    };

    const fullscreen = async () => {
        await graphInstance?.fullscreen();
    };

    useEffect(() => {
        // Equivalent to onMounted in Vue
        // console.log('Component mounted');
    }, []);

    return (
        <div
            className={`rg-toolbar rg-xs-toolbar rg-toolbar-h-${(positionH || options.toolBarPositionH || 'left')} rg-toolbar-v-${(positionV || options.toolBarPositionV || 'bottom')} rg-toolbar-${(direction || options.toolBarDirection || 'h')}`}>
            <div title="Full Screen" className="rg-mb-button" style={{marginTop: 0}} onClick={fullscreen}>
                <RGIcons iconName="icon-quanping"/>
            </div>
            <>
                <div className="rg-mb-button" onClick={() => doZoom(20)}>
                    <RGIcons iconName="icon-fangda"/>
                </div>
                <div className="rg-current-zoom" onClick={zoomToFit}>{`${Math.round(options.canvasZoom)}%`}</div>
                <div className="rg-mb-button" style={{marginTop: 0}} onClick={() => doZoom(-20)}>
                    <RGIcons iconName="icon-suoxiao"/>
                </div>
            </>
            {options.layout.supportAutoLayout && (
                <div
                    title={options.layout.autoLayouting ? 'Stop Force Layout' : 'Start Force Layout'}
                    className={`rg-mb-button ${options.layout.autoLayouting ? 'rg-mb-button-on' : ''}`}
                    onClick={toggleAutoLayout}
                >
                    {
                        !options.layout.autoLayouting ? <RGIcons iconName="icon-zidong"/>
                            : <RGIcons iconName="icon-lianjiezhong" className="rg-loading-icon"/>
                    }
                </div>
            )}
            {children}
        </div>
    );
};

export default GraphXsToolBar;
