// packages/platforms/svelte/src/core4svelte/widgets/GraphOperateStuff.svelte
<script lang="ts">
    import { useGraphInstance } from '../../hooks/useGraphInstance';
    import RGNodePeel from '../RGNodePeel.svelte';
    import GraphMoveOperator from './GraphMoveOperator.svelte';
    import GraphLoading from './GraphLoading.svelte';
    import {useGraphStore} from "../../hooks/useGraphStore";

    const graphInstance = useGraphInstance();
    const {optionsStore} = useGraphStore();
    $: options = $optionsStore;
</script>

{#if options}
    <div class="rg-operate">
        <div class="rg-creating-container">
            {#if options.creatingNodePlot && options.showTemplateNode && options.newNodeTemplate}
                <RGNodePeel nodeProps={options.newNodeTemplate}>
                    <svelte:fragment slot="node" let:node>
                        <slot name="node" {node} />
                    </svelte:fragment>
                </RGNodePeel>
            {/if}

            {#if options.creatingSelection}
                <div
                        class="rg-selection"
                        style:transform="translate({options.selectionView.x}px, {options.selectionView.y}px)"
                        style:width="{options.selectionView.width}px"
                        style:height="{options.selectionView.height}px"
                ></div>
            {/if}
        </div>

        <GraphMoveOperator />
        <GraphLoading />
    </div>
{/if}

// packages/platforms/react/src/relation-graph/src/core4react/widgets/GraphOperateStuff.tsx
import React from 'react';
import RGNodePeel from '../RGNodePeel';
import {RGNode, RGNodeSlotProps} from '../../../../../../../types';
import GraphMoveOperator from "./GraphMoveOperator";
import GraphLoading from './GraphLoading';
import {useGraphInstance} from "../../hooks/useGraphInstance";
import {useGraphStore} from "../../hooks/useGraphStore";

export interface GraphOperateStuffProps {
    nodeSlot?: React.FC<RGNodeSlotProps> | ((props: RGNodeSlotProps) => React.ReactNode)
}

const GraphOperateStuff: React.FC<GraphOperateStuffProps> = ({nodeSlot}) => {
    const graphInstance = useGraphInstance();
    const {options} = useGraphStore();
    return (
        (options) &&
        <div className="rg-operate">
            <div className="rg-creating-container">
                {options.creatingNodePlot && options.showTemplateNode &&
                    <RGNodePeel
                        nodeProps={options.newNodeTemplate}
                        nodeSlot={nodeSlot}
                    />
                }
                {
                    options.creatingSelection &&
                    <div
                        className="rg-selection"
                        style={{
                            transform: `translate(${options.selectionView.x}px, ${options.selectionView.y}px)`,
                            width: options.selectionView.width + 'px',
                            height: options.selectionView.height + 'px',
                        }}
                    >
                    </div>
                }
            </div>
            <GraphMoveOperator/>
            <GraphLoading />
        </div>
    );
};

export default GraphOperateStuff;
