// packages/platforms/vue3/src/relation-graph/src/core4vue3/widgets/RGDebugView.vue
<script lang="ts" setup>
import {computed, ref} from 'vue'
import {devLog} from '../../../../../../../relation-graph-models/utils/RGCommon'
import {useGraphInstance} from "../../hooks/useGraphInstance";

const graphInstance = useGraphInstance();
const options = computed(() => graphInstance.dataStores.optionsRef.value);
const showSettingPanel = ref(false)
const toggleSettingPanel = () => {
    showSettingPanel.value = !showSettingPanel.value
}
const printOptions = () => {
    graphInstance.printOptions();
}
const printData = () => {
    graphInstance.printData();
}
const enableDevlog = () => {
    graphInstance.enableDebugLog(!graphInstance.options.debug)
    devLog('debugLog:', graphInstance.options.debug)
}
</script>
<template>
    <div>
        <div :class="[]" class="rg-setting-panel-button" @click="toggleSettingPanel">
            Debug
        </div>
        <div v-if="showSettingPanel" :class="[]" class="rg-setting-panel">
            <div class="c-debug-tools-row">
                <button @click="printOptions">print options in console</button>
            </div>
            <div class="c-debug-tools-row">
                <button @click="printData">print json data in console</button>
            </div>
            <div class="c-debug-tools-row">debug log status: {{ options.debug }}
                <button @click="enableDevlog">{{ options.debug ? 'disable' : 'enable' }} debug log</button>
            </div>
            <slot />
        </div>
    </div>
</template>

// packages/platforms/react/src/relation-graph/src/core4react/widgets/RGDebugView.tsx
import React, {PropsWithChildren, useState} from 'react';
import { devLog } from '../../../../../../../relation-graph-models/utils/RGCommon';
import {useAutoUpdateView, useGraphInstance} from "../../hooks/useGraphInstance";
import {useGraphStore} from "../../hooks/useGraphStore";

const RGDebugView: React.FC<PropsWithChildren<{}>> = ({children}) => {
  const graphInstance = useGraphInstance();
  useAutoUpdateView();
  const {options} = useGraphStore();
  const [showSettingPanel, setShowSettingPanel] = useState(false);
  const toggleSettingPanel = () => {
    setShowSettingPanel(!showSettingPanel);
  };
  const printOptions = () => {
    graphInstance.printOptions();
  };
  const printData = () => {
    graphInstance.getGraphJsonData();
  };
  const enableDevlog = () => {
    graphInstance.enableDebugLog(!options.debug);
    devLog('debugLog:', options.debug);
    updateView();
  };
  return (
    <div>
      <div className="rg-setting-panel-button" onClick={()=>{toggleSettingPanel();}}>
        Debug
      </div>
      {
        showSettingPanel &&
        <div className="rg-setting-panel">
          <div className="c-debug-tools-row">
            <button onClick={()=>{printOptions();}}>print options in console</button>
          </div>
          <div className="c-debug-tools-row">
            <button onClick={()=>{printData();}}>print json data in console</button>
          </div>
          <div className="c-debug-tools-row">
            debug log status: {options.debug ? 'true' : 'false'}
            <button onClick={()=>{enableDevlog();}}>
              { options.debug ? 'disable' : 'enable' } debug log
            </button>
          </div>
          {children}
        </div>
      }
    </div>
  );
};

export default RGDebugView;
