// packages/platforms/vue2/src/core4vue/widgets/RGDebugView.vue
<template>
    <div>
        <div :class="[]" class="rg-setting-panel-button" @click="toggleSettingPanel">
            Debug
        </div>
        <div v-if="showSettingPanel" :class="[]" class="rg-setting-panel">
            <div class="c-debug-tools-row">
                <button @click="printOptions">print options in console</button>
            </div>
            <div class="c-debug-tools-row">
                <button @click="printData">print json data in console</button>
            </div>
            <div class="c-debug-tools-row">debug log status: {{ options.debug }}
                <button @click="enableDevlog">{{ options.debug ? 'disable' : 'enable' }} debug log</button>
            </div>
            <slot/>
        </div>
    </div>
</template>

<script lang="ts">

import {devLog} from '../../../../../relation-graph-models/utils/RGCommon';

export default {
    name: 'RGDebugView',
    data() {
        return {
            showSettingPanel: false
        };
    },
    inject: ['graphStore'],
    computed: {
        graphInstance() {
            return this.graphStore.graphInstance;
        },
        options() {
            return this.graphStore.options;
        }
    },
    methods: {
        toggleSettingPanel() {
            this.showSettingPanel = !this.showSettingPanel;
        },
        printOptions() {
            this.graphInstance.printOptions();
        },
        printData() {
            this.graphInstance.printData();
        },
        enableDevlog() {
            this.graphInstance.enableDebugLog(!this.options.debug);
            devLog('debugLog:', this.options.debug);
        }
    }
};
</script>

// packages/platforms/react/src/relation-graph/src/core4react/widgets/RGDebugView.tsx
import React, {PropsWithChildren, useState} from 'react';
import { devLog } from '../../../../../../../relation-graph-models/utils/RGCommon';
import {useAutoUpdateView, useGraphInstance} from "../../hooks/useGraphInstance";
import {useGraphStore} from "../../hooks/useGraphStore";

const RGDebugView: React.FC<PropsWithChildren<{}>> = ({children}) => {
  const graphInstance = useGraphInstance();
  useAutoUpdateView();
  const {options} = useGraphStore();
  const [showSettingPanel, setShowSettingPanel] = useState(false);
  const toggleSettingPanel = () => {
    setShowSettingPanel(!showSettingPanel);
  };
  const printOptions = () => {
    graphInstance.printOptions();
  };
  const printData = () => {
    graphInstance.getGraphJsonData();
  };
  const enableDevlog = () => {
    graphInstance.enableDebugLog(!options.debug);
    devLog('debugLog:', options.debug);
    updateView();
  };
  return (
    <div>
      <div className="rg-setting-panel-button" onClick={()=>{toggleSettingPanel();}}>
        Debug
      </div>
      {
        showSettingPanel &&
        <div className="rg-setting-panel">
          <div className="c-debug-tools-row">
            <button onClick={()=>{printOptions();}}>print options in console</button>
          </div>
          <div className="c-debug-tools-row">
            <button onClick={()=>{printData();}}>print json data in console</button>
          </div>
          <div className="c-debug-tools-row">
            debug log status: {options.debug ? 'true' : 'false'}
            <button onClick={()=>{enableDevlog();}}>
              { options.debug ? 'disable' : 'enable' } debug log
            </button>
          </div>
          {children}
        </div>
      }
    </div>
  );
};

export default RGDebugView;
