// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGProvider.vue
<script lang="ts" setup>
import {RelationGraphCore} from '../../../../../../relation-graph-models/models/RelationGraphCore'
import {
    defineRGDataProviderComponent,
    generateNewRGInstance
} from "../hooks/useRGDataProvider";

interface RGProviderProps {
    relationGraphCore?: new (...args: any[]) => RelationGraphCore;
    forLinker?: boolean;
}
const props = defineProps<RGProviderProps>();

const graphInstance = generateNewRGInstance(props.relationGraphCore, props.forLinker);
const rgDataProvider = defineRGDataProviderComponent(graphInstance);
</script>
<template>
    <rgDataProvider>
        <slot />
    </rgDataProvider>
</template>

// packages/platforms/svelte/src/RGProvider.svelte
<script lang="ts">
    import RGProvider4Instance from "./core4svelte/RGProvider4Instance.svelte";
    import {getOrGenerateRGInstance} from "./hooks/useRGDataProvider";
    import {RelationGraphCore} from "../../../relation-graph-models/models/RelationGraphCore";

    export let relationGraphCore: (new (...args: any[]) => RelationGraphCore) | undefined = undefined;
    export let isLinker: boolean | undefined = false;
    const graphInstance = getOrGenerateRGInstance(relationGraphCore, isLinker);
</script>
<RGProvider4Instance {graphInstance}>
    <slot/>
</RGProvider4Instance>
