// packages/platforms/react/src/relation-graph/src/core4react/editing/RGMiniView.tsx
import React, {useEffect, useRef} from 'react';
import {RGMiniViewProps} from "../../../../../../../types";
import {useAutoUpdateView, useGraphInstance} from "../../hooks/useGraphInstance";
import {useGraphStore} from "../../hooks/useGraphStore";

const RGMiniView: React.FC<RGMiniViewProps> = ({className, style, position = 'br', width, height}) => {
    const graphInstance = useGraphInstance();
    useAutoUpdateView();
    const {options} = useGraphStore();
    const $rgMiniView = useRef<HTMLDivElement>(null);
    const $rgMiniViewCanvas = useRef<HTMLCanvasElement>(null);

    useEffect(() => {
        graphInstance.onMiniViewMounted();
        graphInstance.setMiniViewCanvas($rgMiniViewCanvas.current!);

        return () => {
            graphInstance.onMiniViewUnMounted();
        };
    }, []);

    const onMouseDown = (e: React.MouseEvent) => {
        graphInstance.onVisibleViewHandleDragStart(e.nativeEvent);
    };

    const onClickCanvas = async (e: React.MouseEvent) => {
        graphInstance.resetByVisiableView(e.nativeEvent);
    };

    return (
        <div
            className={`rg-miniview rg-miniview-${position} ${className || ''}`}
            ref={$rgMiniView}
            style={{
                ...style,
                '--miniview-width': width,
                '--miniview-height': height
            }}
        >
            <div className="rg-miniview-container">
                <canvas
                    ref={$rgMiniViewCanvas}
                    className={
                        options.miniViewVisibleHandle.emptyContent
                            ? 'rg-mv-canvas-reset'
                            : ''
                    }
                    onClick={onClickCanvas}
                />
                <div
                    className="rg-mv-visible-area"
                    onMouseDown={onMouseDown}
                    style={{
                        transform: `translate(${options.miniViewVisibleHandle.x}px, ${options.miniViewVisibleHandle.y}px)`,
                        // left: `${options.miniViewVisibleHandle.x}px`,
                        // top: `${options.miniViewVisibleHandle.y}px`,
                        width: options.miniViewVisibleHandle.width + 'px',
                        height: options.miniViewVisibleHandle.height + 'px',
                    }}
                ></div>
            </div>
        </div>
    );
};

export default RGMiniView;

// packages/platforms/vue2/src/core4vue/editing/RGMiniView.vue
<template>
    <div
            class="rg-miniview"
            :class="[
                'rg-miniview-' + position,
                $attrs.className
            ]"
            ref="rgMiniView"
            :style="{
                ...$attrs.style,
                '--miniview-width': width,
                '--miniview-height': height
            }"
    >
        <div class="rg-miniview-container">
            <canvas
                    ref="rgMiniViewCanvas"
                    :class="{
                      'rg-mv-canvas-reset': miniViewVisibleHandle.emptyContent
                      }"
                    @click="onClickCanvas"
            />
            <div
                    class="rg-mv-visible-area"
                    @mousedown="onMouseDown"
                    :style="{
                        transform: `translate(${miniViewVisibleHandle.x}px, ${miniViewVisibleHandle.y}px)`,
                        width: miniViewVisibleHandle.width + 'px',
                        height: miniViewVisibleHandle.height + 'px'
                    }"
            ></div>
        </div>
    </div>
</template>

<script lang="ts">
import {RGUserEvent} from "../../../../../types";

export default {
    name: 'RGMiniView',
    components: {},
    props: {
        position: {
            mustUseProp: false,
            default: 'br',
            type: String
        },
        width: {
            mustUseProp: false,
            type: String
        },
        height: {
            mustUseProp: false,
            type: String
        }
    },
    inject: ['graphStore'],
    computed: {
        graphInstance() {
            return this.graphStore.graphInstance;
        },
        options() {
            return this.graphStore.options;
        },
        miniViewVisibleHandle() {
            return this.options.miniViewVisibleHandle;
        }
    },
    data() {
        return {};
    },
    mounted() {
        this.graphInstance.onMiniViewMounted();
        this.graphInstance.setMiniViewCanvas(this.$refs.rgMiniViewCanvas);
    },
    methods: {
        onMouseDown(e: RGUserEvent) {
            this.graphInstance.onVisibleViewHandleDragStart(e);
        },
        onClickCanvas(e: RGUserEvent) {
            this.graphInstance.resetByVisiableView(e);
        }
    },
    beforeDestroy() {
        this.graphInstance.onMiniViewUnMounted();
    }
};
</script>

<style scoped>
</style>
