// packages/platforms/vue3/src/relation-graph/src/core4vue3/editing/RGEditingConnectController.vue
<template>
    <div
            v-if="options.nodeConnectController.show"
            class="rg-editing-connect-ctrl"
            ref="connectBoxRef"
            :style="{
                transform: `translate(${options.nodeConnectController.x}px, ${options.nodeConnectController.y}px)`,
                width: options.nodeConnectController.width + 'px',
                height: options.nodeConnectController.height + 'px',
            }"
    >
        <slot :mouseUpOnJunctionPoint="mouseUpOnJunctionPoint"
              :mouseUpOnJunctionPointWithOffset="mouseUpOnJunctionPointWithOffset">
            <RGEditingConnectPoints :mouseUpOnJunctionPoint="mouseUpOnJunctionPoint"
                                    :mouseUpOnJunctionPointWithOffset="mouseUpOnJunctionPointWithOffset"/>
        </slot>
    </div>
</template>

<script lang="ts" setup>
import {computed, ref} from 'vue';
import RGEditingConnectPoints from "./RGEditingConnectPoints.vue";
import {
    JsonLine, JsonLineLike,
    RGJunctionPoint, RGLineTarget,
    RGNode,
    RGPosition,
    RGUserEvent
} from "../../../../../../../types";
import {devLog} from "../../../../../../../relation-graph-models/utils/RGCommon";
import {useGraphInstance} from "../../hooks/useGraphInstance";

const graphInstance = useGraphInstance();
const options = computed(() => graphInstance.dataStores.optionsRef.value);
const props = defineProps<{}>();
const connectBoxRef = ref();
const mouseUpOnJunctionPoint = (junctionPoint: RGJunctionPoint, $event: RGUserEvent) => {
    graphInstance.onLineVertexBeDroppedOnConnectController(junctionPoint, $event, undefined, (fromNode, toNode, newLineJson) => {
        devLog('onLineVertexBeDropped:callback:', newLineJson);
        // graphInstance.value.defaultLineVertexBeChangedHandler(fromNode, toNode, newLineJson);
    });
};
const mouseUpOnJunctionPointWithOffset = (junctionPoint: RGJunctionPoint, $event: RGUserEvent) => {
    graphInstance.onLineVertexBeDroppedOnConnectController(junctionPoint, $event, connectBoxRef.value, (fromNode, toNode, newLineJson) => {
        devLog('onLineVertexBeDropped:callback:', newLineJson);
        // graphInstance.value.defaultLineVertexBeChangedHandler(fromNode, toNode, newLineJson);
    });
};
</script>

<style scoped>
</style>

// packages/platforms/svelte/src/core4svelte/editing/RGEditingConnectController.svelte
<script lang="ts">
    import { useGraphInstance } from '../../hooks/useGraphInstance';
    import RGEditingConnectPoints from './RGEditingConnectPoints.svelte';
    import { devLog } from '../../../../../relation-graph-models/utils/RGCommon';
    import type {
        JsonLine,
        RGJunctionPoint,
        RGNode,
        RGPosition,
        RGUserEvent
    } from '../../../../../types';
    import {useGraphStore} from "../../hooks/useGraphStore";

    let connectBoxRef: HTMLElement;

    const graphInstance = useGraphInstance();
    const {optionsStore} = useGraphStore();
    $: options = $optionsStore;

    function mouseUpOnJunctionPoint(junctionPoint: RGJunctionPoint, e: RGUserEvent) {
        graphInstance.onLineVertexBeDroppedOnConnectController(junctionPoint, e, undefined, (fromNode, toNode, newLineJson) => {
            devLog('onLineVertexBeDropped:callback:', newLineJson);
            // graphInstance.defaultLineVertexBeChangedHandler(fromNode, toNode, newLineJson);
        });
    }

    function mouseUpOnJunctionPointWithOffset(junctionPoint: RGJunctionPoint, e: RGUserEvent) {
        graphInstance.onLineVertexBeDroppedOnConnectController(junctionPoint, e, connectBoxRef, (fromNode, toNode, newLineJson) => {
            devLog('onLineVertexBeDropped:callback:', newLineJson);
            // graphInstance.defaultLineVertexBeChangedHandler(fromNode, toNode, newLineJson);
        });
    }
</script>

{#if options.nodeConnectController.show}
    <div
            class="rg-editing-connect-ctrl"
            bind:this={connectBoxRef}
            style:transform="translate({options.nodeConnectController.x}px, {options.nodeConnectController.y}px)"
            style:width="{options.nodeConnectController.width}px"
            style:height="{options.nodeConnectController.height}px"
    >
        <!--
            Svelte 插槽传递 prop 的方式。
            如果有默认插槽内容，可以像这样提供默认实现。
        -->
        <slot
                {mouseUpOnJunctionPoint}
                {mouseUpOnJunctionPointWithOffset}
        >
            <RGEditingConnectPoints
                    {mouseUpOnJunctionPoint}
                    {mouseUpOnJunctionPointWithOffset}
            />
        </slot>
    </div>
{/if}
