// packages/platforms/react/src/relation-graph/src/core4react/widgets/GraphMoveOperator.tsx
import React from 'react';
import {useGraphInstance} from "../../hooks/useGraphInstance";

const GraphMoveOperator: React.FC = () => {
    const graphInstance = useGraphInstance();
    const canvasMoveMode = graphInstance?.options.canvasMoveMode || false;
    // Event handler for touchpad
    const onTouchpadMouseDown = (e: React.MouseEvent | React.TouchEvent) => {
        if (graphInstance) {
            graphInstance.startMoveCanvas(e.nativeEvent, true);
        }
    };
    return (
        <div
            className={`rg-move-operator ${canvasMoveMode ? 'rg-move-operator-active' : ''}`}
        >
            <div
                className="rg-move-touchpad"
                onMouseDown={onTouchpadMouseDown}
                onTouchStart={onTouchpadMouseDown}
            ></div>
        </div>
    )
};
export default GraphMoveOperator;

// packages/platforms/vue2/src/core4vue/widgets/GraphMoveOperator.vue
<template>
    <div
            class="rg-move-operator"
            :class="{
      'rg-move-operator-active': canvasMoveMode
    }"
    >
        <div
                class="rg-move-touchpad"
                @mousedown="onTouchpadMouseDown"
                @touchstart="onTouchpadMouseDown"
        >
        </div>
    </div>
</template>

<script lang="ts">

export default {
    name: 'GraphMoveOperator',
    components: {},
    data() {
        return {};
    },
    inject: ['graphStore'],
    computed: {
        graphInstance() {
            return this.graphStore.graphInstance;
        },
        options() {
            return this.graphStore.options;
        },
        canvasMoveMode() {
            return this.options.canvasMoveMode;
        }
    },
    mounted() {
    },
    methods: {
        async onTouchpadMouseDown(e) {
            this.graphInstance.startMoveCanvas(e, true);
        }
    },
    beforeDestroy() {
    }
};
</script>
<style lang="scss" scoped>

</style>
