// packages/platforms/svelte/src/core4svelte/widgets/GraphOperateStuff.svelte
<script lang="ts">
    import { useGraphInstance } from '../../hooks/useGraphInstance';
    import RGNodePeel from '../RGNodePeel.svelte';
    import GraphMoveOperator from './GraphMoveOperator.svelte';
    import GraphLoading from './GraphLoading.svelte';
    import {useGraphStore} from "../../hooks/useGraphStore";

    const graphInstance = useGraphInstance();
    const {optionsStore} = useGraphStore();
    $: options = $optionsStore;
</script>

{#if options}
    <div class="rg-operate">
        <div class="rg-creating-container">
            {#if options.creatingNodePlot && options.showTemplateNode && options.newNodeTemplate}
                <RGNodePeel nodeProps={options.newNodeTemplate}>
                    <svelte:fragment slot="node" let:node>
                        <slot name="node" {node} />
                    </svelte:fragment>
                </RGNodePeel>
            {/if}

            {#if options.creatingSelection}
                <div
                        class="rg-selection"
                        style:transform="translate({options.selectionView.x}px, {options.selectionView.y}px)"
                        style:width="{options.selectionView.width}px"
                        style:height="{options.selectionView.height}px"
                ></div>
            {/if}
        </div>

        <GraphMoveOperator />
        <GraphLoading />
    </div>
{/if}

// packages/platforms/vue2/src/core4vue/widgets/GraphOperateStuff.vue
<template>
    <div v-if="options" class="rg-operate">
        <div class="rg-creating-container">
            <RGNodePeel v-if="options.creatingNodePlot && options.showTemplateNode"
                         :node-props="options.newNodeTemplate">
                <template #node>
                    <slot :node="options.newNodeTemplate" name="node"/>
                </template>
            </RGNodePeel>
            <div
                    v-if="options.creatingSelection"
                    class="rg-selection"
                    :style="{
                            transform: `translate(${options.selectionView.x}px, ${options.selectionView.y}px)`,
                            width: options.selectionView.width + 'px',
                            height: options.selectionView.height + 'px',
                      }"
            >

            </div>
        </div>
        <GraphLoading />
        <GraphMoveOperator/>
    </div>
</template>

<script lang="ts">
import RGNodePeel from "../RGNodePeel.vue";
import GraphMoveOperator from "./GraphMoveOperator.vue";
import GraphLoading from "./GraphLoading.vue";

export default {
    name: 'GraphOperateStuff',
    components: {GraphLoading, GraphMoveOperator, RGNodePeel},
    inject: ['graphStore'],
    computed: {
        graphInstance() {
            return this.graphStore.graphInstance;
        },
        options() {
            return this.graphStore.options;
        }
    },
    mounted() {
    },
    methods: {}
};
</script>

<style scoped>
</style>
