// packages/platforms/svelte/src/core4svelte/widgets/GraphWatermark.svelte
<script lang="ts">
    import { onMount, onDestroy } from 'svelte';
    import { useGraphInstance } from '../../hooks/useGraphInstance';
    import type { RGWidgetPosition } from '../../../../../types';
    import {useGraphStore} from "../../hooks/useGraphStore";

    export let forImage = true;
    export let forDisplay = false;
    export let position: RGWidgetPosition = 'br';
    export let width: string | undefined = undefined;
    export let height: string | undefined = undefined;

    let watermarkRef: HTMLElement;

    const graphInstance = useGraphInstance();
    const {optionsStore} = useGraphStore();
    $: options = $optionsStore;

    $: show = (() => {
        let visible = false;
        if (options.snapshotting) {
            if (forImage === false) {
                visible = false;
            } else {
                visible = true;
            }
        } else {
            if (forDisplay === true) {
                visible = true;
            } else {
                visible = false;
            }
        }
        return visible;
    })();

    onMount(() => {
        if (watermarkRef) {
            graphInstance.setWatermarkDom(watermarkRef, forImage, forDisplay, position);
        }
    });

    onDestroy(() => {
        // 注意：Svelte 的 onDestroy 不接受参数，这里只是调用方法，不需要参数
        // 但 setWatermarkDom 需要参数来做清理判断
        graphInstance.setWatermarkDom(null, forImage, forDisplay, position);
    });
</script>

<div
        bind:this={watermarkRef}
        class="rg-watermark rg-watermark-{position || 'br'}"
        style:display={show ? '' : 'none'}
        style:--watermark-width={width}
        style:--watermark-height={height}
>
    <slot />
</div>

// packages/platforms/vue2/src/core4vue/widgets/GraphWatermark.vue
<template>
    <div
            v-show="show"
            class="rg-watermark"
            :class="['rg-watermark-' + position]"
            ref="watermarkRef"
            :style="{
                '--watermark-width': width,
                '--watermark-height': height
            }"
    >
        <slot/>
    </div>
</template>

<script lang="ts">

export default {
    name: 'GraphWatermark',
    components: {},
    props: {
        forImage: {
            mustUseProp: false,
            default: true,
            type: Boolean
        },
        forDisplay: {
            mustUseProp: false,
            default: true,
            type: Boolean
        },
        position: {
            mustUseProp: false,
            default: 'br',
            type: String
        },
        width: {
            mustUseProp: false,
            type: String
        },
        height: {
            mustUseProp: false,
            type: String
        }
    },
    inject: ['graphStore'],
    computed: {
        graphInstance() {
            return this.graphStore.graphInstance;
        },
        options() {
            return this.graphStore.options;
        },
        show() {
            let show = false;
            if (this.options.snapshotting) {
                if (this.forImage === false) {
                    show = false;
                } else {
                    show = true;
                }
            } else {
                if (this.forDisplay === true) {
                    show = true;
                } else {
                    show = false;
                }
            }
            return show;
        }
    },
    mounted() {
        this.graphInstance.setWatermarkDom(this.$refs.watermarkRef, this.forImage, this.forDisplay, this.position);
    },
    methods: {},
    beforeDestroy() {
        this.graphInstance.setWatermarkDom(null, this.forImage, this.forDisplay);
    }
};
</script>

<style scoped>
</style>
