// packages/platforms/svelte/src/core4svelte/RGCanvasContent4Lines.svelte
<script lang="ts">
    import { useGraphInstance } from '../hooks/useGraphInstance';
    import { useGraphStore } from '../hooks/useGraphStore';
    import RGGraphDefs from './RGGraphDefs.svelte';
    import RGLinePeel from './RGLinePeel.svelte';

    export let showEasyView = false;
    export let defaultLineTextOnPath = false;
    export let checkedLineId = '';
    export let graphInstanceId: string | undefined = undefined;

    const graphInstance = useGraphInstance();
    const { shouldRenderLinesStore } = useGraphStore();

    $: shouldRenderLines = $shouldRenderLinesStore!;
    $: allLineConfigList = graphInstance.getShouldRenderLines(shouldRenderLines);
</script>

<div class="rg-lines-container rg-lines-container-normal-lines">
    <svg class="rg-lines-svg" xmlns="http://www.w3.org/2000/svg">
        <RGGraphDefs />
        {#if !showEasyView}
            {#each allLineConfigList as thisLine (thisLine.id)}
                {#if thisLine.hidden !== true}
                    <RGLinePeel
                            line={thisLine}
                            checked={thisLine.id === checkedLineId}
                            {graphInstanceId}
                            {defaultLineTextOnPath}
                    >
                        <svelte:fragment slot="line" let:lineConfig let:checked let:defaultLineTextOnPath let:graphInstanceId>
                            <slot name="line" {lineConfig} {checked} {defaultLineTextOnPath} {graphInstanceId} />
                        </svelte:fragment>
                    </RGLinePeel>
                {/if}
            {/each}
        {/if}
    </svg>
    <div class="rg-linetext-container" />
</div>

// packages/platforms/vue2/src/core4vue/RGCanvasContent4Lines.vue
<template>
    <div ref="rgCanvas" class="rg-lines-container rg-lines-container-normal-lines">
        <svg class="rg-lines-svg"
             xmlns="http://www.w3.org/2000/svg">
            <RGGraphDefs />
            <template  v-if="!showEasyView">
                <template v-for="thisLine in allLineConfigList">
                    <RGLinePeel
                            v-if="thisLine.hidden !== true"
                            :key="'l-'+thisLine.id"
                            :line="thisLine"
                            :defaultLineTextOnPath="defaultLineTextOnPath"
                            :checked="thisLine.id === checkedLineId"
                            :graph-instance-id="graphInstanceId"
                    >
                        <template #line="lineSlotProps">
                            <slot v-bind="lineSlotProps" name="line"/>
                        </template>
                    </RGLinePeel>
                </template>
            </template>
        </svg>
        <div class="rg-linetext-container"/>
    </div>
</template>

<script lang="ts">
import RGLinePeel from './RGLinePeel.vue';
import {devLog} from '../../../../relation-graph-models/utils/RGCommon';
import RGGraphDefs from "./RGGraphDefs.vue";

export default {
    name: 'RGCanvasContent4Lines',
    components: {RGLinePeel, RGGraphDefs},
    data() {
        return {};
    },
    props: [
        'showEasyView',
        'defaultLineTextOnPath',
        'checkedLineId',
        'graphInstanceId'
    ],
    inject: ['graphStore'],
    computed: {
        graphInstance() {
            return this.graphStore.graphInstance;
        },
        allLineConfigList() {
            return this.graphInstance.getShouldRenderLines();
        }
    },
    created() {
        devLog('[RGCanvasContent4Lines created]');
    },
    mounted() {
        devLog('[RGCanvasContent4Lines mounted]');
        this.init();
    },
    beforeDestroy() {
    },
    methods: {
        init() {
        },
    }
};
</script>
