// packages/platforms/react/src/relation-graph/src/core4react/RGEasyView.tsx
import React, {MutableRefObject, useEffect, useRef} from 'react';
import {RGCanvasProps} from './RGCanvas';
import { devLog } from '../../../../../../relation-graph-models/utils/RGCommon';
import {useGraphInstance} from "../hooks/useGraphInstance";
import {useGraphStore} from "../hooks/useGraphStore";

const RGCanvas: React.FC<RGCanvasProps> = (canvasProps) => {
  const graphInstance = useGraphInstance();
  const {options} = useGraphStore();
  const rgEasyCanvas$ = useRef() as MutableRefObject<HTMLCanvasElement>;

  useEffect(() => {
    devLog('[RGEasyView mounted]');
    graphInstance.setEasyViewCanvas(rgEasyCanvas$.current!);
    return () => {
        devLog('[RGEasyView UnMounted]');
    }
  }, []);

  return (
    <div className={`rg-easy-view ${options.showEasyView ? 'rg-easy-view-active' : ''}`}>
      <canvas ref={rgEasyCanvas$} />
    </div>
  );
};

export default RGCanvas;

// packages/platforms/vue2/src/core4vue/RGEasyView.vue
<template>
    <div class="rg-easy-view" :class="{'rg-easy-view-active':options.showEasyView}">
        <canvas ref="rgEasyCanvas" style="width: 100%;height: 100%;" />
    </div>
</template>

<script lang="ts">
import { devLog } from '../../../../relation-graph-models/utils/RGCommon';

export default {
    name: 'RGEasyView',
    components: {},
    data() {
        return {
        };
    },
    inject: ['graphStore'],
    computed: {
        graphInstance() {
            return this.graphStore.graphInstance;
        },
        options() {
            return this.graphStore.options;
        }
    },
    created() {
        devLog('[RGEasyView created]');
    },
    mounted() {
        devLog('[RGEasyView mounted]');
        const graphInstance = this.graphInstance;
        graphInstance.setEasyViewCanvas && graphInstance.setEasyViewCanvas(this.$refs.rgEasyCanvas);
        this.init();
    },
    beforeDestroy() {
    },
    methods: {
        init() {
        },
    }
};
</script>
