// packages/platforms/svelte/src/core4svelte/RGGraphDefs.svelte
<script lang="ts">
    import { useGraphInstance } from '../hooks/useGraphInstance';
    import {useGraphStore} from "../hooks/useGraphStore";

    export let forElementLines: boolean = false;

    const graphInstance = useGraphInstance();
    const {optionsStore} = useGraphStore();
    $: options = $optionsStore;
</script>

<defs>
    <marker
            id={options.instanceId + '-arrow-default'}
            markerWidth={options.defaultLineMarker.markerWidth}
            markerHeight={options.defaultLineMarker.markerHeight}
            refX={options.defaultLineMarker.refX}
            refY={options.defaultLineMarker.refY}
            markerUnits="userSpaceOnUse"
            orient="auto"
            viewBox={options.defaultLineMarker.viewBox}
    >
        <path style="fill: context-stroke;" d={options.defaultLineMarker.data} />
    </marker>
    <marker
            id={options.instanceId + '-start-arrow-default'}
            markerWidth={options.defaultLineMarker.markerWidth}
            markerHeight={options.defaultLineMarker.markerHeight}
            refX={options.defaultLineMarker.refX}
            refY={options.defaultLineMarker.refY}
            markerUnits="userSpaceOnUse"
            orient="auto-start-reverse"
            viewBox={options.defaultLineMarker.viewBox}
    >
        <path style="fill: context-stroke;" d={options.defaultLineMarker.data} />
    </marker>
    <slot />
</defs>

// packages/platforms/vue2/src/core4vue/RGGraphDefs.vue
<template>
    <defs>
        <marker
                :id="options.instanceId+'-arrow-default'"
                :markerWidth="options.defaultLineMarker.markerWidth"
                :markerHeight="options.defaultLineMarker.markerHeight"
                :refX="options.defaultLineMarker.refX"
                :refY="options.defaultLineMarker.refY"
                markerUnits="userSpaceOnUse"
                orient="auto"
                :viewBox="options.defaultLineMarker.viewBox"
        >
            <path style="fill: context-stroke;" :d="options.defaultLineMarker.data"/>
        </marker>
        <marker
                :id="options.instanceId+'-start-arrow-default'"
                :markerWidth="options.defaultLineMarker.markerWidth"
                :markerHeight="options.defaultLineMarker.markerHeight"
                :refX="options.defaultLineMarker.refX"
                :refY="options.defaultLineMarker.refY"
                markerUnits="userSpaceOnUse"
                orient="auto-start-reverse"
                :viewBox="options.defaultLineMarker.viewBox"
        >
            <path style="fill: context-stroke;" :d="options.defaultLineMarker.data"/>
        </marker>
        <slot/>
    </defs>
</template>

<script lang="ts">

export default {
    name: 'RGGraphDefs',
    components: {},
    props: {
        forElementLines: {
            type: Boolean,
            mustUseProp: false,
            default: false
        }
    },
    data() {
        return {};
    },
    inject: ['graphStore'],
    computed: {
        graphInstance() {
            return this.graphStore.graphInstance;
        },
        options() {
            return this.graphStore.options;
        }
    }
};
</script>
