// packages/platforms/react/src/relation-graph/src/core4react/RGLineContent.tsx
import React, {useMemo} from 'react';
import {RGLinePathInfo, RGLineShape, RGLineSlotProps} from "../../../../../../types";
import RGLineText from "./RGLineText";
import RGLinePath from "./RGLinePath";
import {useGraphInstance} from "../hooks/useGraphInstance";

const RGLineContent: React.FC<RGLineSlotProps> = (
    {
        lineConfig,
        defaultLineTextOnPath,
        graphInstanceId,
        checked
    }
) => {
    const graphInstance = useGraphInstance();
    const linePathInfo = useMemo<RGLinePathInfo>(() => graphInstance.generateLinePath(lineConfig), [lineConfig]);
    const onLineClick = (e: React.MouseEvent | React.TouchEvent) => {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        graphInstance.onLineClick(lineConfig.line, e.nativeEvent);
    };
    const useTextOnPath = (lineConfig.line.useTextOnPath || defaultLineTextOnPath);
    const useSvgTextPath = useTextOnPath && (lineConfig.line.lineShape !== RGLineShape.StandardStraight);
    const showNormalLineText = !useSvgTextPath;
    const textStyle = graphInstance.generateLineTextStyle(lineConfig, linePathInfo);
    return (<>
        <RGLinePath
            lineConfig={lineConfig}
            linePathInfo={linePathInfo}
            onLineClick={onLineClick}
            useTextOnPath={useSvgTextPath}
            checked={checked}
            graphInstanceId={graphInstanceId}
        />
        {lineConfig.line.text && showNormalLineText && <RGLineText
            lineConfig={lineConfig}
            linePathInfo={linePathInfo}
            checked={checked}
        >
            {
                <div
                    className={`rg-line-label ${useTextOnPath ? 'rg-line-label-on-path':''}`}
                    style={{
                        ...textStyle.cssStyles
                    }}
                    onTouchStart={onLineClick}
                    onClick={onLineClick}
                >
                    {textStyle.text}
                </div>
            }
        </RGLineText>}
    </>);
};

export default RGLineContent;

// packages/platforms/vue2/src/core4vue/RGLineContent.vue
<template>
    <RGLinePath
            :lineConfig="lineConfig"
            :linePathInfo="linePathInfo"
            :useTextOnPath="useSvgTextPath"
            :graph-instance-id="graphInstanceId"
            :checked="checked"
            @onLineClick="onLineClick"
    >
        <RGLineText
                v-if="lineConfig.line.text && !useSvgTextPath"
                :lineConfig="lineConfig"
                :linePathInfo="linePathInfo"
                :checked="checked"
                @onLineClick="onLineClick"
        >
            <div
                :class="`rg-line-label ${useTextOnPath ? 'rg-line-label-on-path':''}`"
                :style="{
                    ...textStyle.cssStyles
                }"
                @touchstart="onLineClick"
                @click="onLineClick"
            >
                {{ textStyle.text }}
            </div>
        </RGLineText>
    </RGLinePath>
</template>

<script lang="ts">
import RGLinePath from "./RGLinePath";
import RGLineText from "./RGLineText";
import {RGLineShape} from "../../../../types";

export default {
    name: 'RGLineContent',
    components: {RGLinePath, RGLineText},
    props: [
        'lineConfig',
        'defaultLineTextOnPath',
        'graphInstanceId',
        'checked'
    ],
    data() {
        return {};
    },
    inject: ['graphStore'],
    computed: {
        graphInstance() {
            return this.graphStore.graphInstance;
        },
        useTextOnPath() {
            return this.lineConfig.line.useTextOnPath || this.defaultLineTextOnPath;
        },
        useSvgTextPath() {
            return this.useTextOnPath && (this.lineConfig.line.lineShape !== RGLineShape.StandardStraight);
        },
        linePathInfo() {
            return this.graphInstance.generateLinePath(this.lineConfig);
        },
        textStyle() {
            return this.graphInstance.generateLineTextStyle(this.lineConfig, this.linePathInfo)
        },
    },
    watch: {},
    methods: {
        onLineClick(e) {
            this.graphInstance.onLineClick(this.lineConfig.line, e);
        }
    }
};
</script>

<style scoped>
</style>
