// packages/platforms/vue2/src/core4vue/RelationGraphUI.vue
<template>
    <div
        ref="relationGraphRef"
        :id="`relation-graph-ins-${graphOptions && graphOptions.instanceId}`"
        :class="graphClass"
        tabindex="1"
        :style="graphStyle"
    >
        <GraphXsToolBar v-if="graphOptions && graphOptions.showToolBar"/>
        <RGCanvas>
            <template #line="lineSlotProps">
                <slot v-bind="lineSlotProps" name="line"/>
            </template>
            <template #canvas-plug-behind>
                <slot name="canvas-plug-behind"/>
            </template>
            <template #canvas-plug-above>
                <slot name="canvas-plug-above"/>
            </template>
            <template #node="nodeSlotProps">
                <slot v-bind="nodeSlotProps" name="node"/>
            </template>
            <template #node-expand-button="nodeExpandButtonSlotProps">
                <slot name="node-expand-button" v-bind="nodeExpandButtonSlotProps"/>
            </template>
            <template #background>
                <slot name="background"/>
            </template>
        </RGCanvas>
        <GraphOperateStuff>
            <template #line="lineSlotProps">
                <slot v-bind="lineSlotProps" name="line"/>
            </template>
        </GraphOperateStuff>
        <div class="rg-graph-plugs">
            <div class="rg-view-slot">
                <slot name="view"/>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
import {devLog} from '../../../../relation-graph-models/utils/RGCommon';
import RGCanvas from './RGCanvas.vue';
import GraphXsToolBar from './widgets/GraphXsToolBar.vue';
import GraphOperateStuff from './widgets/GraphOperateStuff.vue';
import {RGTips} from "../../../../relation-graph-models/utils/RGTips";
import type {RGOptionsFull} from "../../../../types";

export default {
    name: 'RelationGraphUI',
    components: {
        GraphOperateStuff, GraphXsToolBar, RGCanvas
    },
    props: {
        initialData: {
            mustUseProp: false,
            default: () => {
                return null;
            },
            type: Object
        }
    },
    inject: ['graphStore'],
    computed: {
        graphOptions(): RGOptionsFull {
            return this.graphStore.options;
        },
        graphClass(): string[] {
            const options = this.graphOptions;
            const classList = ['relation-graph'];
            if (options) {
                if (options.creatingLinePlot) {
                    classList.push('rg-creating-line');
                }
                if (options.dragEventAction === 'move') {
                    classList.push('rg-move-mode');
                }
                if (options.enableNodeXYAnimation) {
                    classList.push('rg-enable-node-xy-animation');
                }
                if (options.enableCanvasTransformAnimation) {
                    classList.push('rg-enable-canvas-animation');
                }
            }
            return classList;
        },
        graphStyle() {
            const options = this.graphOptions;
            if (!options) return { width: '100%', height: '100%' };
            return {
                width: '100%',
                height: options.viewHeight ? options.viewHeight : '100%',
                '--rg-checked-item-bg-color': options.checkedItemBackgroundColor,
                '--rg-background-color': options.backgroundColor,
                '--rg-node-color': options.defaultNodeColor,
                '--rg-node-border-color': options.defaultNodeBorderColor,
                '--rg-node-border-width': options.defaultNodeBorderWidth + 'px',
                '--rg-node-border-radius': options.defaultNodeBorderRadius + 'px',
                '--rg-line-color': options.defaultLineColor,
                '--rg-line-width': options.defaultLineWidth + 'px',
            };
        }
    },
    mounted() {
        // console.log('---------------------------RelationGraphUI mounted---------------------------');
        const graphInstance = this.graphStore.graphInstance;
        graphInstance.setDom(this.$refs.relationGraphRef);
        graphInstance.ready();
        if (this.initialData) {
            graphInstance.applyInitialData(this.initialData);
        }
    },
    methods: {
        async setJsonData() {
            throw new Error(RGTips.setJsonData4Vue2)
        }
    },
    beforeDestroy() {
        devLog('beforeDestroy:relation-graph');
        const graphInstance = this.graphStore.graphInstance;
        graphInstance.beforeUnmount();
    }
};
</script>

// packages/platforms/svelte/src/core4svelte/RelationGraphUI.svelte
<script lang="ts">
    import {onDestroy, onMount} from 'svelte';
    import {useGraphInstance} from '../hooks/useGraphInstance';
    import {useGraphStore} from '../hooks/useGraphStore';
    import GraphOperateStuff from './widgets/GraphOperateStuff.svelte';
    import GraphXsToolBar from './widgets/GraphXsToolBar.svelte';
    import RGCanvas from './RGCanvas.svelte';
    import RGLineContent from "./RGLineContent.svelte";

    let relationGraphRef: HTMLElement;
    let graphReady = false;

    const graphInstance = useGraphInstance();
    const {optionsStore} = useGraphStore();
    $: options = $optionsStore;

    onMount(() => {
        // console.log('[RelationGraphUI mounted]');
        graphInstance.setDom(relationGraphRef);
        graphReady = true;
    });

    onDestroy(() => {
        graphInstance.beforeUnmount();
    });
</script>

<div
        bind:this={relationGraphRef}
        id={options ? 'relation-graph-ins-' + options.instanceId : undefined}
        tabindex={1}
        class={[
            'relation-graph',
            options?.creatingLinePlot ? 'rg-creating-line' : '',
            options?.dragEventAction === 'move' ? 'rg-move-mode' : '',
            options?.enableNodeXYAnimation ? 'rg-enable-node-xy-animation' : '',
            options?.enableCanvasTransformAnimation ? 'rg-enable-canvas-animation' : ''
          ].filter(Boolean).join(' ')}
        style:width="100%"
        style:height={options?.viewHeight ? options.viewHeight : '100%'}
        style:opacity={graphReady ? 1 : 0}
        style:--rg-checked-item-bg-color={options?.checkedItemBackgroundColor}
        style:--rg-background-color={options?.backgroundColor}
        style:--rg-node-color={options?.defaultNodeColor}
        style:--rg-node-border-color={options?.defaultNodeBorderColor}
        style:--rg-node-border-width={options?.defaultNodeBorderWidth + 'px'}
        style:--rg-node-border-radius={options?.defaultNodeBorderRadius + 'px'}
        style:--rg-line-color={options?.defaultLineColor}
        style:--rg-line-width={options?.defaultLineWidth + 'px'}
>
    {#if options && graphReady}
        {#if options.showToolBar}
            <GraphXsToolBar/>
        {/if}

        <RGCanvas>
            <!-- 转发插槽 node -->
            <svelte:fragment slot="node" let:node let:checked let:dragging>
                <slot name="node" {node} {checked} {dragging}/>
            </svelte:fragment>

            <svelte:fragment slot="line" let:lineConfig let:checked let:defaultLineTextOnPath let:graphInstanceId>
                <slot name="line" {lineConfig} {checked} {defaultLineTextOnPath} {graphInstanceId} />
            </svelte:fragment>

            <!-- 转发插槽 canvas-plug-behind -->
            <svelte:fragment slot="canvas-behind">
                <slot name="canvas-behind"/>
            </svelte:fragment>

            <!-- 转发插槽 canvas-plug-above -->
            <svelte:fragment slot="canvas-above">
                <slot name="canvas-above"/>
            </svelte:fragment>
            <svelte:fragment slot="background">
                <slot name="background" />
            </svelte:fragment>

            <!-- 转发插槽 node-expand-button -->
            <svelte:fragment slot="node-expand-button" let:node let:expandHolderPosition let:expandOrCollapseNode>
                <slot
                        name="node-expand-button"
                        {node}
                        {expandHolderPosition}
                        {expandOrCollapseNode}
                />
            </svelte:fragment>
        </RGCanvas>

        <GraphOperateStuff>
            <svelte:fragment slot="node" let:node>
                <slot name="node" {node}/>
            </svelte:fragment>
        </GraphOperateStuff>

        <div class="rg-graph-plugs">
            <div class="rg-view-slot">
                <slot name="view"/>
            </div>
        </div>
    {/if}
</div>
