// packages/platforms/vue2/src/core4vue/RelationLinkerCanvas.vue
<template>
    <div
            class="rg-map"
            :class="[
                (options.canvasOpacity === 1 && 'rg-map-ready')
                 ]"
    >
        <div :style="canvasSizeAndPosition" class="rg-map-canvas rg-canvas-behind"
             style="position: relative;pointer-events: all;user-select: text;">
            <div class="rg-canvas-slot rg-canvas-slot-behind">
                <slot name="canvas-plug-behind"/>
            </div>
        </div>
        <div ref="rgCanvasRef" :style="canvasSizeAndPosition" class="rg-map-canvas"
             style="position: absolute;left:0px;top:0px;z-index: 9;">
            <RGCanvasContent
                    :show-easy-view="options.showEasyView"
                    :creating-line="!!(options.creatingLinePlot && options.newLinkTemplate.fromNode)"
                    :default-expand-holder-position="options.defaultExpandHolderPosition"
                    :draggingNodeId="options.draggingNodeId"
                    :checkedNodeId="options.checkedNodeId"
                    :defaultLineTextOnPath="options.defaultLineTextOnPath"
                    :checked-line-id="options.checkedLineId"
                    :graph-instance-id="options.instanceId"
            >
                <template #line="{lineConfig}">
                    <slot :lineConfig="lineConfig" name="line"/>
                </template>
            </RGCanvasContent>
        </div>
    </div>
</template>

<script lang="ts">
import {devLog} from '../../../../relation-graph-models/utils/RGCommon';
import RGCanvasContent from "./RGCanvasContent.vue";

export default {
    name: 'RelationLinkerCanvas',
    components: {RGCanvasContent},
    data() {
        return {};
    },
    inject: ['graphStore'],
    computed: {
        graphInstance() {
            return this.graphStore.graphInstance;
        },
        options() {
            return this.graphStore.options;
        },
        canvasSizeAndPosition() {
            return {
                'background-color': 'transparent',
                'text-wrap': 'unset',
                position: 'relative',
                width: '100%',
                height: 'fit-content'
            };
        }
    },
    watch: {},
    created() {
        devLog('[RGCanvas created]');
    },
    mounted() {
        devLog('[RGCanvas mounted]');
        this.graphInstance.setCanvasDom(this.$refs.rgCanvasRef);
    },
    beforeDestroy() {
    },
    methods: {}
};
</script>

// packages/platforms/svelte/src/core4svelte/RelationLinkerCanvas.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { useGraphInstance } from '../hooks/useGraphInstance';
    import RGCanvasContent from './RGCanvasContent.svelte';
    import {useGraphStore} from "../hooks/useGraphStore";

    const graphInstance = useGraphInstance();
    let rgCanvasRef: HTMLElement;

    const {optionsStore} = useGraphStore();
    $: options = $optionsStore;

    $: canvasSizeAndPosition = {
        'background-color': 'transparent',
        'text-wrap': 'unset', // 注意：text-wrap 是较新的 CSS 属性，某些浏览器可能不兼容
        'position': 'relative',
        'width': '100%',
        'height': 'fit-content',
    };

    onMount(() => {
        // console.log('[RelationLinkerCanvas mounted]');
        graphInstance.setCanvasDom(rgCanvasRef);
    });
</script>

<div
        class="rg-map {options.canvasOpacity === 1 ? 'rg-map-ready' : ''}"
>
    <div
            style:background-color={canvasSizeAndPosition['background-color']}
            style:position={canvasSizeAndPosition.position}
            style:width={canvasSizeAndPosition.width}
            style:height={canvasSizeAndPosition.height}
            class="rg-map-canvas rg-canvas-behind"
    >
        <div
                class="rg-canvas-slot rg-canvas-slot-behind"
                style="position: relative; pointer-events: all; user-select: text;"
        >
            <slot name="canvas-behind" />
        </div>
    </div>

    <div
            bind:this={rgCanvasRef}
            style:background-color={canvasSizeAndPosition['background-color']}
            style:position="absolute"
            style:left="0px"
            style:top="0px"
            style:z-index="9"
            style:width={canvasSizeAndPosition.width}
            style:height={canvasSizeAndPosition.height}
            class="rg-map-canvas"
    >
        <RGCanvasContent
            showEasyView={options.showEasyView}
            creatingLine={!!(options.creatingLinePlot && options.newLinkTemplate.fromNode)}
            defaultExpandHolderPosition={options.defaultExpandHolderPosition}
            draggingNodeId={options.draggingNodeId}
            checkedNodeId={options.checkedNodeId}
            defaultLineTextOnPath={options.defaultLineTextOnPath}
            checkedLineId={options.checkedLineId}
            graphInstanceId={options.instanceId}
        >
            <svelte:fragment slot="line" let:lineConfig let:checked let:defaultLineTextOnPath let:graphInstanceId>
                <slot name="line" {lineConfig} {checked} {defaultLineTextOnPath} {graphInstanceId} />
            </svelte:fragment>
        </RGCanvasContent>
    </div>
</div>
