// packages/platforms/vue2/src/core4vue/RGCanvasContent4Nodes.vue
<template>
    <div class="rg-nodes-container">
        <RGNodePeel v-for="thisNode in allNodeConfigList"
                    :key="thisNode.id"
                    :node-props="thisNode"
                    :default-expand-holder-position="defaultExpandHolderPosition"
                    :dragging="thisNode.id===draggingNodeId"
                    :checked="thisNode.id===checkedNodeId"
        >
            <template #node="nodeSlotProps">
                <slot v-bind="nodeSlotProps" name="node"/>
            </template>
            <template #node-expand-button="nodeExpandButtonSlotProps">
                <slot name="node-expand-button" v-bind="nodeExpandButtonSlotProps" />
            </template>
        </RGNodePeel>
    </div>
</template>

<script lang="ts">
import RGNodePeel from './RGNodePeel.vue';
import {devLog} from '../../../../relation-graph-models/utils/RGCommon';

export default {
    name: 'RGCanvasContent4Nodes',
    components: {RGNodePeel},
    data() {
        return {};
    },
    props: [
        'defaultExpandHolderPosition',
        'draggingNodeId',
        'checkedNodeId'
    ],
    inject: ['graphStore'],
    computed: {
        graphInstance() {
            return this.graphStore.graphInstance;
        },
        allNodeConfigList() {
            return this.graphInstance.getShouldRenderNodes();
        }
    },
    created() {
        devLog('[RGCanvasContent4Nodes created]');
    },
    mounted() {
        devLog('[RGCanvasContent4Nodes mounted]');
        this.init();
    },
    beforeDestroy() {
    },
    methods: {
        init() {
        },
    }
};
</script>

// packages/platforms/svelte/src/core4svelte/RGCanvasContent4Nodes.svelte
<script lang="ts">
    import { useGraphInstance } from '../hooks/useGraphInstance';
    import { useGraphStore } from '../hooks/useGraphStore';
    import RGNodePeel from './RGNodePeel.svelte';

    export let defaultExpandHolderPosition = '';
    export let draggingNodeId = '';
    export let checkedNodeId = '';

    const graphInstance = useGraphInstance();
    const { shouldRenderNodesStore } = useGraphStore();

    $: shouldRenderNodes = $shouldRenderNodesStore!;
    $: allNodeConfigList = graphInstance.getShouldRenderNodes(shouldRenderNodes);
</script>

<div class="rg-nodes-container">
    {#each allNodeConfigList as thisNode (thisNode.id)}
        <RGNodePeel
                nodeProps={thisNode}
                {defaultExpandHolderPosition}
                dragging={thisNode.id === draggingNodeId}
                checked={thisNode.id === checkedNodeId}
        >
            <svelte:fragment slot="node" let:node let:checked let:dragging>
                <slot name="node" {node} {checked} {dragging} />
            </svelte:fragment>

            <svelte:fragment slot="node-expand-button" let:node let:expandHolderPosition let:expandOrCollapseNode>
                <slot
                        name="node-expand-button"
                        {node}
                        {expandHolderPosition}
                        {expandOrCollapseNode}
                />
            </svelte:fragment>
        </RGNodePeel>
    {/each}
</div>
