// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGCanvasContent4CreatingLine.vue
<script lang="ts" setup>
import {computed, onMounted} from 'vue'
import {devLog} from '../../../../../../relation-graph-models/utils/RGCommon'
import RGLineContent from "./RGLineContent.vue";
import {useGraphInstance} from "../hooks/useGraphInstance";
defineProps<{
    defaultLineTextOnPath?: boolean,
    checkedLineId?: string,
    graphInstanceId?: string,
}>()
const graphInstance = useGraphInstance();
const creatingLineConfig = computed(() => {
    // console.error('creatingLineConfig: computed!')
    return graphInstance.generateCreatingLineConfig(graphInstance.dataStores.optionsRef.value);
});
onMounted(() => {
    devLog('[RGCanvas mounted]')
})
</script>
<template>
    <div class="rg-lines-container rg-lines-container-el-lines">
        <div class="rg-linetext-container"/>
        <svg class="rg-lines-svg rg-lines-svg-el-lines" xmlns="http://www.w3.org/2000/svg">
            <slot name="line" :line-config="creatingLineConfig">
                <RGLineContent
                        :line-config="creatingLineConfig"
                        :defaultLineTextOnPath="defaultLineTextOnPath"
                        :graph-instance-id="graphInstanceId"
                />
            </slot>
        </svg>
    </div>
</template>
<style scoped>
</style>

// packages/platforms/svelte/src/core4svelte/RGCanvasContent4CreatingLine.svelte
<script lang="ts">
    import { useGraphInstance } from '../hooks/useGraphInstance';
    import { useGraphStore } from '../hooks/useGraphStore';
    import RGLineContent from './RGLineContent.svelte';

    export let defaultLineTextOnPath = false;
    export let graphInstanceId: string | undefined = undefined;

    const graphInstance = useGraphInstance();
    const { optionsStore } = useGraphStore();

    $: options = $optionsStore!;
    $: creatingLineConfig = graphInstance.generateCreatingLineConfig(options);
</script>

<div class="rg-lines-container rg-lines-container-el-lines">
    <div class="rg-linetext-container" />
    <svg class="rg-lines-svg rg-lines-svg-el-lines" xmlns="http://www.w3.org/2000/svg">
        <slot name="line" lineConfig={creatingLineConfig}>
            <RGLineContent lineConfig={creatingLineConfig} checked={false} {defaultLineTextOnPath} {graphInstanceId} />
        </slot>
    </svg>
</div>
