// packages/platforms/react/src/relation-graph/src/core4react/RGCanvasContent4FakeLines.tsx
import React, {useEffect} from 'react';
import RGGraphRefs from './RGGraphRefs';
import RGLinePeel from "./RGLinePeel";
import {useGraphInstance} from "../hooks/useGraphInstance";
import {useGraphStore} from "../hooks/useGraphStore";
import type {RGLineSlotProps} from "../../../../../../types";

export interface RGCanvasContent4FakeLinesProps {
    showEasyView: boolean,
    lineSlot?: React.FC<RGLineSlotProps> | ((props: RGLineSlotProps) => React.ReactNode)
    defaultLineTextOnPath?: boolean,
    checkedLineId?: string,
    graphInstanceId?: string,
}

const RGCanvasContent4FakeLines: React.FC<RGCanvasContent4FakeLinesProps> = (
    {
        showEasyView,
        lineSlot,
        defaultLineTextOnPath,
        checkedLineId,
        graphInstanceId,
    }
) => {
    const graphInstance = useGraphInstance();
    const { shouldRenderFakeLines } = useGraphStore();
    const allFakeLineConfigList = !showEasyView ? graphInstance.getShouldRenderFakeLines(shouldRenderFakeLines) : [];
    return (
        <div className="rg-lines-container rg-lines-container-el-lines">
            <div className="rg-linetext-container"/>
            <svg className="rg-lines-svg rg-lines-svg-el-lines"
                 xmlns="http://www.w3.org/2000/svg">
                {<RGGraphRefs forElementLines={true}/>}
                {
                    !showEasyView && allFakeLineConfigList.map(line =>
                        (line.hidden !== true) &&
                        <RGLinePeel
                            key={line.id}
                            line={line}
                            lineSlot={lineSlot}
                            defaultLineTextOnPath={defaultLineTextOnPath}
                            checked={line.id === checkedLineId}
                            graphInstanceId={graphInstanceId}
                        />
                    )
                }
            </svg>
        </div>
    );
};

export default RGCanvasContent4FakeLines;

// packages/platforms/svelte/src/core4svelte/RGCanvasContent4FakeLines.svelte
<script lang="ts">
    import { useGraphInstance } from '../hooks/useGraphInstance';
    import { useGraphStore } from '../hooks/useGraphStore';
    import RGGraphDefs from './RGGraphDefs.svelte';
    import RGLinePeel from './RGLinePeel.svelte';

    export let showEasyView = false;
    export let defaultLineTextOnPath = false;
    export let checkedLineId = '';
    export let graphInstanceId: string | undefined = undefined;

    const graphInstance = useGraphInstance();
    const { shouldRenderFakeLinesStore } = useGraphStore();

    $: shouldRenderFakeLines = $shouldRenderFakeLinesStore!;
    $: allFakeLineConfigList = graphInstance.getShouldRenderFakeLines(shouldRenderFakeLines);
</script>

<div class="rg-lines-container rg-lines-container-el-lines">
    <svg class="rg-lines-svg rg-lines-svg-el-lines" xmlns="http://www.w3.org/2000/svg">
        <RGGraphDefs forElementLines={true} />
        {#if !showEasyView}
            {#each allFakeLineConfigList as line (line.id)}
                {#if line.hidden !== true}
                    <RGLinePeel
                            {line}
                            {defaultLineTextOnPath}
                            checked={line.id === checkedLineId}
                            {graphInstanceId}
                    >
                        <svelte:fragment slot="line" let:lineConfig let:checked let:defaultLineTextOnPath let:graphInstanceId>
                            <slot name="line" {lineConfig} {checked} {defaultLineTextOnPath} {graphInstanceId} />
                        </svelte:fragment>
                    </RGLinePeel>
                {/if}
            {/each}
        {/if}
    </svg>
    <div class="rg-linetext-container" />
</div>
