// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGCanvasContent4Lines.vue
<script lang="ts" setup>
import {computed, onMounted} from 'vue'
import {devLog} from '../../../../../../relation-graph-models/utils/RGCommon'
import RGGraphDefs from "./RGGraphDefs.vue";
import RGLinePeel from "./RGLinePeel.vue";
import {useGraphInstance} from "../hooks/useGraphInstance";
defineProps<{
    showEasyView: boolean,
    defaultLineTextOnPath?: boolean,
    checkedLineId?: string,
    graphInstanceId?: string,
}>()
const graphInstance = useGraphInstance();
const allLineConfigList = computed(() => {
    // console.error('allLineConfigList: computed!')
    return graphInstance.getShouldRenderLines(graphInstance.dataStores.shouldRenderLinesRef.value);
});
onMounted(() => {
    devLog('[RGCanvas mounted]')
})
</script>
<template>
    <div class="rg-lines-container rg-lines-container-normal-lines">
        <div class="rg-linetext-container"/>
        <svg class="rg-lines-svg"
             xmlns="http://www.w3.org/2000/svg">
            <RGGraphDefs />
            <template v-if="!showEasyView">
                <template v-for="thisLine in allLineConfigList" :key="thisLine.id">
                    <RGLinePeel
                            v-if="thisLine.hidden !== true"
                            :key="'l-'+thisLine.id"
                            :line="thisLine"
                            :defaultLineTextOnPath="defaultLineTextOnPath"
                            :checked="thisLine.id === checkedLineId"
                            :graph-instance-id="graphInstanceId"
                    >
                        <template #line="lineSlotProps">
                            <slot v-bind="lineSlotProps" name="line"/>
                        </template>
                    </RGLinePeel>
                </template>
            </template>
        </svg>
    </div>
</template>
<style scoped>
</style>

// packages/platforms/svelte/src/core4svelte/RGCanvasContent4Lines.svelte
<script lang="ts">
    import { useGraphInstance } from '../hooks/useGraphInstance';
    import { useGraphStore } from '../hooks/useGraphStore';
    import RGGraphDefs from './RGGraphDefs.svelte';
    import RGLinePeel from './RGLinePeel.svelte';

    export let showEasyView = false;
    export let defaultLineTextOnPath = false;
    export let checkedLineId = '';
    export let graphInstanceId: string | undefined = undefined;

    const graphInstance = useGraphInstance();
    const { shouldRenderLinesStore } = useGraphStore();

    $: shouldRenderLines = $shouldRenderLinesStore!;
    $: allLineConfigList = graphInstance.getShouldRenderLines(shouldRenderLines);
</script>

<div class="rg-lines-container rg-lines-container-normal-lines">
    <svg class="rg-lines-svg" xmlns="http://www.w3.org/2000/svg">
        <RGGraphDefs />
        {#if !showEasyView}
            {#each allLineConfigList as thisLine (thisLine.id)}
                {#if thisLine.hidden !== true}
                    <RGLinePeel
                            line={thisLine}
                            checked={thisLine.id === checkedLineId}
                            {graphInstanceId}
                            {defaultLineTextOnPath}
                    >
                        <svelte:fragment slot="line" let:lineConfig let:checked let:defaultLineTextOnPath let:graphInstanceId>
                            <slot name="line" {lineConfig} {checked} {defaultLineTextOnPath} {graphInstanceId} />
                        </svelte:fragment>
                    </RGLinePeel>
                {/if}
            {/each}
        {/if}
    </svg>
    <div class="rg-linetext-container" />
</div>
