// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGEasyView.vue
<script lang="ts" setup>
import { computed, onMounted, ref } from 'vue'
import { devLog } from '../../../../../../relation-graph-models/utils/RGCommon'
import {useGraphInstance} from "../hooks/useGraphInstance";
const graphInstance = useGraphInstance();
const $rgEasyCanvas = ref<HTMLCanvasElement>()
const options = computed(() => graphInstance.dataStores.optionsRef.value);
onMounted(() => {
  devLog('[RGEasyView mounted]');
    graphInstance.setEasyViewCanvas && graphInstance.setEasyViewCanvas($rgEasyCanvas.value!);
})
</script>
<template>
    <div class="rg-easy-view" :class="{'rg-easy-view-active':options.showEasyView}">
        <canvas ref="$rgEasyCanvas" style="width: 100%;height: 100%;" />
    </div>
</template>

// packages/platforms/svelte/src/core4svelte/RGEasyView.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { useGraphInstance } from '../hooks/useGraphInstance';
    import {useGraphStore} from "../hooks/useGraphStore";

    let rgEasyCanvas: HTMLCanvasElement;

    const graphInstance = useGraphInstance();
    const {optionsStore} = useGraphStore();
    $: options = $optionsStore;

    onMount(() => {
        // console.log('[RGEasyView mounted]');
        if (graphInstance.setEasyViewCanvas) {
            graphInstance.setEasyViewCanvas(rgEasyCanvas);
        }
    });
</script>

<div class="rg-easy-view" class:rg-easy-view-active={options.showEasyView}>
    <canvas bind:this={rgEasyCanvas} style="width: 100%; height: 100%;" />
</div>
