// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGGraphDefs.vue
<script lang="ts" setup>
import { computed } from 'vue'
import {useGraphInstance} from "../hooks/useGraphInstance";

const graphInstance = useGraphInstance();
const options = computed(() => graphInstance.dataStores.optionsRef.value);
const props = defineProps<{
  forElementLines?: boolean
}>()
</script>
<template>
  <defs>
    <marker
      :id="options.instanceId+'-arrow-default'"
      :markerWidth="options.defaultLineMarker.markerWidth"
      :markerHeight="options.defaultLineMarker.markerHeight"
      :refX="options.defaultLineMarker.refX"
      :refY="options.defaultLineMarker.refY"
      markerUnits="userSpaceOnUse"
      orient="auto"
      :viewBox="options.defaultLineMarker.viewBox"
    >
      <path style="fill: context-stroke;" :d="options.defaultLineMarker.data" />
    </marker>
    <marker
      :id="options.instanceId+'-start-arrow-default'"
      :markerWidth="options.defaultLineMarker.markerWidth"
      :markerHeight="options.defaultLineMarker.markerHeight"
      :refX="options.defaultLineMarker.refX"
      :refY="options.defaultLineMarker.refY"
      markerUnits="userSpaceOnUse"
      orient="auto-start-reverse"
      :viewBox="options.defaultLineMarker.viewBox"
    >
      <path style="fill: context-stroke;" :d="options.defaultLineMarker.data"  />
    </marker>
    <slot />
  </defs>
</template>
<style scoped>
</style>

// packages/platforms/svelte/src/core4svelte/RGGraphDefs.svelte
<script lang="ts">
    import { useGraphInstance } from '../hooks/useGraphInstance';
    import {useGraphStore} from "../hooks/useGraphStore";

    export let forElementLines: boolean = false;

    const graphInstance = useGraphInstance();
    const {optionsStore} = useGraphStore();
    $: options = $optionsStore;
</script>

<defs>
    <marker
            id={options.instanceId + '-arrow-default'}
            markerWidth={options.defaultLineMarker.markerWidth}
            markerHeight={options.defaultLineMarker.markerHeight}
            refX={options.defaultLineMarker.refX}
            refY={options.defaultLineMarker.refY}
            markerUnits="userSpaceOnUse"
            orient="auto"
            viewBox={options.defaultLineMarker.viewBox}
    >
        <path style="fill: context-stroke;" d={options.defaultLineMarker.data} />
    </marker>
    <marker
            id={options.instanceId + '-start-arrow-default'}
            markerWidth={options.defaultLineMarker.markerWidth}
            markerHeight={options.defaultLineMarker.markerHeight}
            refX={options.defaultLineMarker.refX}
            refY={options.defaultLineMarker.refY}
            markerUnits="userSpaceOnUse"
            orient="auto-start-reverse"
            viewBox={options.defaultLineMarker.viewBox}
    >
        <path style="fill: context-stroke;" d={options.defaultLineMarker.data} />
    </marker>
    <slot />
</defs>
