// packages/platforms/react/src/relation-graph/src/core4react/RGLineText.tsx
import React, {PropsWithChildren} from 'react';
import {createPortal} from "react-dom";
import {RGLineTextProps} from "../../../../../../types";
import {useGraphInstance} from "../hooks/useGraphInstance";

const RGLineText: React.FC<PropsWithChildren<RGLineTextProps>> = ({children, lineConfig, checked}) => {
    const graphInstance = useGraphInstance();
    if (!graphInstance) return null;
    const lineTextContainer = graphInstance.getLineTextContainer(lineConfig?.line);
    if (!lineTextContainer) return null;
    const line = lineConfig.line;
    const selected = line.selected;
    return createPortal(<div
        className={[
            'rg-line-peel',
            line.className,
            (checked && 'rg-line-checked'),
            ((line.disablePointEvent || line.opacity === 0) && 'rg-line-disable-events'),
            (selected && 'rg-line-selected')
        ].filter(Boolean).join(' ')}
        data-id={line.id}
        style={{
            '--rg-line-color': line.color,
            '--rg-line-fontsize': (lineConfig.line.fontSize ? `${lineConfig.line.fontSize}px` : undefined),
            '--rg-line-opacity': line.opacity,
            '--rg-line-fontcolor': line.fontColor,
            ...(line.cssVars || {})
        }}
    >
        {children}
    </div>, lineTextContainer);
};
export default RGLineText;

// packages/platforms/svelte/src/core4svelte/RGLineText.svelte
<script lang="ts">
    import { useGraphInstance } from '../hooks/useGraphInstance';
    import type { RGLineTextProps } from '../../../../types';
    import {useGraphStore} from "../hooks/useGraphStore";

    export let lineConfig: RGLineTextProps['lineConfig'];
    // Svelte 中一般不需要导出 linePathInfo 如果它只在 RGLineContent 中被计算，
    // 但如果 props 接口需要，可以加上：
    export let linePathInfo: any = undefined;
    export let checked: boolean | undefined;

    const graphInstance = useGraphInstance();
    $: line = lineConfig?.line;
    $: lineTextContainer = graphInstance.getLineTextContainer(lineConfig?.line);

    /**
     * Svelte Action for Teleporting
     */
    function portal(node: HTMLElement, target: HTMLElement | undefined) {
        function update(newTarget: HTMLElement | undefined) {
            if (newTarget) {
                newTarget.appendChild(node);
            } else if (node.parentNode) {
                node.parentNode.removeChild(node);
            }
        }
        update(target);
        return {
            update,
            destroy() {
                if (node.parentNode) node.parentNode.removeChild(node);
            }
        };
    }

</script>

{#if line && lineTextContainer}
    <foreignObject style="display: none;">
    <div
            use:portal={lineTextContainer}
            class={[
      'rg-line-peel',
      line.className,
      checked ? 'rg-line-checked' : '',
      (line.disablePointEvent || line.opacity === 0) ? 'rg-line-disable-events' : '',
      line.selected ? 'rg-line-selected' : ''
    ].filter(Boolean).join(' ')}
            data-id={line.id}
            style:--rg-line-color={line.color}
            style:--rg-line-fontsize={line.fontSize ? line.fontSize + 'px' : undefined}
            style:--rg-line-opacity={line.opacity}
            style:--rg-line-fontcolor={line.fontColor}
    >
        <slot />
    </div>
    </foreignObject>
{/if}
