// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGLinePeel.vue
<script lang="ts" setup>
import {computed} from 'vue'
import {
    RGLinePeelProps,
} from '../../../../../../types';
import RGLineContent from "./RGLineContent.vue";
import {useGraphInstance} from "../hooks/useGraphInstance";

const {
    line,
    defaultLineTextOnPath,
    graphInstanceId,
    checked
} = defineProps<RGLinePeelProps>()
const graphInstance = useGraphInstance();

const config = computed(() => {
    return line.isFakeLine ? graphInstance.generateFakeLineConfig(line) : graphInstance.generateLineConfig(line);
})
</script>
<template>
    <g v-if="config">
        <slot
                name="line"
                :line-config="config"
                :defaultLineTextOnPath="defaultLineTextOnPath"
                :graph-instance-id="graphInstanceId"
                :checked="checked"
        >
            <RGLineContent
                    :line-config="config"
                    :defaultLineTextOnPath="defaultLineTextOnPath"
                    :graph-instance-id="graphInstanceId"
                    :checked="checked"
            />
        </slot>
    </g>
</template>

// packages/platforms/svelte/src/core4svelte/RGLinePeel.svelte
<script lang="ts">
    import { useGraphInstance } from '../hooks/useGraphInstance';
    import type { RGLinePeelProps } from '../../../../types';

    // 注意：Svelte中 export let 用于接收 props，直接解构 defineProps 不太一样
    export let line: RGLinePeelProps['line'];
    export let checked: boolean | undefined;
    export let defaultLineTextOnPath: boolean | undefined;
    export let graphInstanceId: string | undefined;

    const graphInstance = useGraphInstance();

    $: lineConfig = line.isFakeLine
        ? graphInstance.generateFakeLineConfig(line)
        : graphInstance.generateLineConfig(line);
</script>

{#if lineConfig}
    <g>
        <slot name="line" {lineConfig} {checked} {graphInstanceId} {defaultLineTextOnPath} />
     </g>
{/if}
