// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGNodePeel.vue
<script lang="ts" setup>
import {computed, onBeforeUnmount, onMounted, ref} from 'vue'
import RGNodeExpandHolder from './RGNodeExpandHolder.vue'
import type {RGNode} from '../../../../../../types';

import {useGraphInstance} from "../hooks/useGraphInstance";

const graphInstance = useGraphInstance();
const props = defineProps<{
    nodeProps: RGNode,
    defaultExpandHolderPosition?: string,
    dragging?: boolean,
    checked?: boolean,
}>()
const nodePeelRef = ref<HTMLElement>()
const borderColor = computed(() => {
    return props.nodeProps.borderColor
});
const borderWidth = computed(() => {
    return props.nodeProps.borderWidth === undefined ? undefined : (props.nodeProps.borderWidth + 'px');
});
const nodeWidth = computed(() => {
    return props.nodeProps.width ? (props.nodeProps.width + 'px') : undefined;
});
const nodeHeight = computed(() => {
    return props.nodeProps.height ? (props.nodeProps.height + 'px') : undefined;
});
const showExpandHolder = computed(() => {
    if (props.nodeProps.expandHolderPosition) {
        return props.nodeProps.expandHolderPosition !== 'hide';
    }
    return (props.defaultExpandHolderPosition && props.defaultExpandHolderPosition !== 'hide' && props.nodeProps.rgChildrenSize > 0)
});
const isVisibleNode = computed(() => {
    // return RGNodesAnalytic.isVisibleNode(props.nodeProps)
    return props.nodeProps.rgCalcedVisibility;
})
const expandOrCollapseNode = (e: MouseEvent) => {
    graphInstance.expandOrCollapseNode(props.nodeProps, e)
}
const onDragStart = (e: MouseEvent | TouchEvent) => {
    graphInstance.onNodeDragStart(props.nodeProps, e);
}
onMounted(() => {
    graphInstance.addNodeResizeListener(nodePeelRef.value!, props.nodeProps)
})
onBeforeUnmount(() => {
    graphInstance.removeNodeResizeListener(nodePeelRef.value!)
})
</script>
<template>
    <div
            v-show="isVisibleNode"
            ref="nodePeelRef"
            :style="{
              // 'left':nodeProps.x + 'px',
              // 'top':nodeProps.y + 'px',
              transform: `translate(${nodeProps.x}px, ${nodeProps.y}px)`,
              '--rg-node-z-index':nodeProps.zIndex ? nodeProps.zIndex : undefined,
              // 'opacity': (nodeProps.opacity>1?nodeProps.opacity/100:nodeProps.opacity),
               '--rg-node-color': nodeProps.color,
               '--rg-node-font-color': nodeProps.fontColor,
               '--rg-node-font-size': nodeProps.fontSize ? (nodeProps.fontSize + 'px') : undefined,
               '--rg-node-border-width': borderWidth,
               '--rg-node-border-radius': nodeProps.borderRadius && (nodeProps.borderRadius + 'px'),
               '--rg-node-border-color': borderColor,
                '--rg-node-width': nodeWidth,
                '--rg-node-height': nodeHeight,
                '--rg-node-opacity': nodeProps.opacity === undefined ? undefined : nodeProps.opacity,
            }"
            :class="[
                    'rg-node-peel',
                    (nodeProps.selected && 'rg-node-selected'),
                    (dragging && 'rg-node-dragging'),
                    (checked && 'rg-node-checked'),
                    ((nodeProps.disablePointEvent || nodeProps.opacity === 0) && 'rg-node-disable-events'),
                    'rg-node-shape-'+(nodeProps.nodeShape===undefined?1:nodeProps.nodeShape),
                    'rg-node-type-'+nodeProps.type,
                    nodeProps.className
            ]"
            :data-id="nodeProps.id"
    >
        <slot
                v-if="showExpandHolder"
                name="node-expand-button"
                :node="nodeProps"
                :expandOrCollapseNode="expandOrCollapseNode"
                :expandHolderPosition="(nodeProps.expandHolderPosition||defaultExpandHolderPosition)"
        >
            <RGNodeExpandHolder
                    :node="nodeProps"
                    :checked="checked"
                    :expandOrCollapseNode="expandOrCollapseNode"
                    :expandHolderPosition="(nodeProps.expandHolderPosition||defaultExpandHolderPosition)"
            />
        </slot>
        <div
                class="rg-node"
                @mousedown.left.stop="onDragStart"
                @touchstart.stop="onDragStart"
        >
            <slot name="node" :node="nodeProps" :checked="checked" :dragging="dragging">
                <div class="rg-node-text">
                    <span>{{nodeProps.text}}</span>
                </div>
            </slot>
        </div>
    </div>
</template>

// packages/platforms/svelte/src/core4svelte/RGNodePeel.svelte
<script lang="ts">
    import { onMount, onDestroy } from 'svelte';
    import { useGraphInstance } from '../hooks/useGraphInstance';
    import type { RGNode } from '../../../../types';

    export let nodeProps: RGNode;
    export let defaultExpandHolderPosition: string | undefined;
    export let dragging: boolean | undefined;
    export let checked: boolean | undefined;
    let nodePeelRef: HTMLElement;


    const graphInstance = useGraphInstance();
    $: borderColor = nodeProps.borderColor;
    $: borderWidth = nodeProps.borderWidth === undefined ? undefined : nodeProps.borderWidth + 'px';
    $: nodeWidth = nodeProps.width ? nodeProps.width + 'px' : undefined;
    $: nodeHeight = nodeProps.height ? nodeProps.height + 'px' : undefined;

    $: expandButtonPosition = nodeProps.expandHolderPosition || defaultExpandHolderPosition || 'hide';
    $: showExpandHolder = (nodeProps.expandHolderPosition && nodeProps.expandHolderPosition !== 'hide') || (expandButtonPosition !== 'hide' && nodeProps.rgChildrenSize > 0);

    $: isVisibleNode = nodeProps.rgCalcedVisibility;

    function expandOrCollapseNode(e: MouseEvent) {
        graphInstance.expandOrCollapseNode(nodeProps, e);
    }

    function onDragStart(e: MouseEvent | TouchEvent) {
        graphInstance.onNodeDragStart(nodeProps, e);
    }

    onMount(() => {
        if (nodePeelRef) {
            graphInstance.addNodeResizeListener(nodePeelRef, nodeProps);
        }
    });

    onDestroy(() => {
        if (nodePeelRef) {
            graphInstance.removeNodeResizeListener(nodePeelRef);
        }
    });
</script>

<div
        bind:this={nodePeelRef}
        class={[
    'rg-node-peel',
    nodeProps.selected ? 'rg-node-selected' : '',
    dragging ? 'rg-node-dragging' : '',
    checked ? 'rg-node-checked' : '',
    (nodeProps.disablePointEvent || nodeProps.opacity === 0) ? 'rg-node-disable-events' : '',
    'rg-node-shape-' + (nodeProps.nodeShape === undefined ? 1 : nodeProps.nodeShape),
    'rg-node-type-' + nodeProps.type,
    nodeProps.className
  ].filter(Boolean).join(' ')}
        data-id={nodeProps.id}
        style:display={isVisibleNode ? '' : 'none'}
        style:transform="translate({nodeProps.x}px, {nodeProps.y}px)"
        style:--rg-node-z-index={nodeProps.zIndex}
        style:--rg-node-color={nodeProps.color}
        style:--rg-node-font-color={nodeProps.fontColor}
        style:--rg-node-font-size={nodeProps.fontSize ? nodeProps.fontSize + 'px' : undefined}
        style:--rg-node-border-width={borderWidth}
        style:--rg-node-border-radius={nodeProps.borderRadius ? nodeProps.borderRadius + 'px' : undefined}
        style:--rg-node-border-color={borderColor}
        style:--rg-node-width={nodeWidth}
        style:--rg-node-height={nodeHeight}
        style:--rg-node-opacity={nodeProps.opacity}
>
    {#if showExpandHolder}
        <slot
                name="node-expand-button"
                node={nodeProps}
                {expandOrCollapseNode}
                expandHolderPosition={expandButtonPosition}
         />
    {/if}

    <!-- svelte-ignore a11y-no-static-element-interactions -->
    <div
            class="rg-node"
            on:mousedown|stopPropagation={onDragStart}
            on:touchstart|stopPropagation={onDragStart}
    >
        <slot name="node" node={nodeProps} {checked} {dragging} />
    </div>
</div>
