// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGNodeExpandHolder.vue
<script lang="ts" setup>
import type {RGNode} from '../../../../../../types';
import {computed} from "vue";
import RGIcons from "./widgets/RGIcons.vue";

const props = defineProps<{
    node: RGNode
    expandOrCollapseNode: (e: MouseEvent) => void
    expandHolderPosition: string
}>();

const expandButtonClass = computed(() => {
    return props.node.expanded === false ? 'c-expanded' : 'c-collapsed'
})
</script>
<template>
    <div
            :class="['rg-node-expand-holder', ('c-expand-positon-'+expandHolderPosition)]"
    >
        <div
            class="rg-node-expand-button"
            :class="expandButtonClass"
            @click.stop="expandOrCollapseNode"
            @touchend.stop="expandOrCollapseNode"
        >
            <RGIcons v-if="node.expanded === false" iconName="icon-fangda" />
            <RGIcons v-else iconName="icon-suoxiao" />
        </div>
    </div>
</template>

// packages/platforms/svelte/src/core4svelte/RGNodeExpandHolder.svelte
<script lang="ts">
    import type { RGNode } from '../../../../types';
    import RGIcons from "./widgets/RGIcons.svelte";

    export let node: RGNode;
    export let expandOrCollapseNode: (e: MouseEvent) => void;
    export let expandHolderPosition: string;

    $: expandButtonClass = node.expanded === false ? 'rg-node-expand-button c-expanded' : 'rg-node-expand-button c-collapsed';
</script>

<div class={['rg-node-expand-holder', 'c-expand-positon-' + expandHolderPosition].join(' ')}>
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <!-- svelte-ignore a11y-no-static-element-interactions -->
    <div
            class={expandButtonClass}
            on:click|stopPropagation={expandOrCollapseNode}
            on:touchend|stopPropagation={expandOrCollapseNode}
    >
        {#if node.expanded === false}
            <RGIcons iconName="icon-fangda" />
        {:else}
            <RGIcons iconName="icon-suoxiao" />
        {/if}
    </div>
</div>
