// packages/platforms/vue3/src/relation-graph/src/core4vue3/RelationLinkerCanvas.vue
<script lang="ts" setup>
import {computed, onMounted, ref} from 'vue'
import {devLog} from '../../../../../../relation-graph-models/utils/RGCommon'
import RGCanvasContent from './RGCanvasContent.vue'
import {useGraphInstance} from "../hooks/useGraphInstance";

const rgCanvasRef = ref<HTMLDivElement>()
const graphInstance = useGraphInstance();

const options = computed(() => graphInstance.dataStores.optionsRef.value);
const canvasSizeAndPosition = computed(() => {
    return {
        'background-color': 'transparent',
        'text-wrap': 'unset',
        position: 'relative',
        width: '100%',
        height: 'fit-content',
    }
})
onMounted(() => {
    devLog('[RGCanvas mounted]')
    graphInstance.setCanvasDom(rgCanvasRef.value!)
})
</script>
<template>
    <div
        class="rg-map"
        :class="[
                (options.canvasOpacity === 1 && 'rg-map-ready')
                 ]"
    >
        <div :style="canvasSizeAndPosition" class="rg-map-canvas rg-canvas-behind">
            <div class="rg-canvas-slot rg-canvas-slot-behind" style="position: relative;pointer-events: all;user-select: text;">
                <slot name="canvas-behind"/>
            </div>
        </div>
        <div ref="rgCanvasRef" :style="canvasSizeAndPosition" class="rg-map-canvas" style="position: absolute;left:0px;top:0px;z-index: 9;">
            <RGCanvasContent
                    :show-easy-view="options.showEasyView"
                    :creating-line="!!(options.creatingLinePlot && options.newLinkTemplate.fromNode)"
                    :default-expand-holder-position="options.defaultExpandHolderPosition"
                    :draggingNodeId="options.draggingNodeId"
                    :checkedNodeId="options.checkedNodeId"
                    :defaultLineTextOnPath="options.defaultLineTextOnPath"
                    :checked-line-id="options.checkedLineId"
                    :graph-instance-id="options.instanceId"
            >
                <template #line="lineSlotProps">
                    <slot v-bind="lineSlotProps" name="line"/>
                </template>
            </RGCanvasContent>
        </div>
    </div>
</template>
<style scoped>
</style>

// packages/platforms/react/src/relation-graph/src/core4react/RelationLinkerCanvas.tsx
import type {MutableRefObject} from 'react';
import React, {PropsWithChildren, useEffect, useRef} from 'react';
import {devLog} from '../../../../../../relation-graph-models/utils/RGCommon';
import {RGLineSlotProps,} from '../../../../../../types';
import RGCanvasContent from "./RGCanvasContent";
import {useGraphInstance} from "../hooks/useGraphInstance";
import {useGraphStore} from "../hooks/useGraphStore";

const RelationLinkerCanvas: React.FC<PropsWithChildren<{
    lineSlot?: React.FC<RGLineSlotProps> | ((props: RGLineSlotProps) => React.ReactNode)
    canvasPlugBehindSlot?: React.ReactNode
}>> = (canvasProps) => {
    const graphInstance = useGraphInstance();
    const {options} = useGraphStore();
    const rgCanvasRef$ = useRef() as MutableRefObject<HTMLDivElement>;
    const canvasSizeAndPosition = {
        backgroundColor: 'transparent',
        textWrap: 'unset',
        position: 'relative',
        width: '100%',
        height: 'fit-content'
    };

    useEffect(() => {
        devLog('[RGCanvas mounted]');
        graphInstance.setCanvasDom(rgCanvasRef$.current!);
        return () => {
            devLog('[RGCanvas UnMounted]');
        }
    }, []);

    return (
        <div
            className={[
                'rg-map',
                (options.canvasOpacity === 1 ? 'rg-map-ready' : '')
            ].join(' ')}
        >
            <div
                style={{
                    ...canvasSizeAndPosition,
                    position: 'relative',
                    pointerEvents: 'all',
                    userSelect: 'text',
                }}
                className="rg-map-canvas rg-canvas-behind"
            >
                <div className="rg-canvas-slot rg-canvas-slot-behind">
                    {canvasProps.canvasPlugBehindSlot}
                </div>
            </div>
            <div
                ref={rgCanvasRef$}
                style={{
                    ...canvasSizeAndPosition,
                    pointerEvents: 'none',
                    userSelect: 'none',
                    left: '0px',
                    top: '0px',
                    zIndex: 9,
                }}
                className="rg-map-canvas"
            >
                <RGCanvasContent
                    lineSlot={canvasProps.lineSlot}
                    showEasyView={options.showEasyView}
                    creatingLine={options.creatingLinePlot && options.newLinkTemplate.fromNode}
                    defaultExpandHolderPosition={options.defaultExpandHolderPosition}
                    draggingNodeId={options.draggingNodeId}
                    checkedNodeId={options.checkedNodeId}
                    defaultLineTextOnPath={options.defaultLineTextOnPath}
                    checkedLineId={options.checkedLineId}
                    graphInstanceId={options.instanceId}
                />
            </div>
        </div>
    );
};

export default RelationLinkerCanvas;
