// packages/platforms/svelte/src/core4svelte/RGCanvasContent.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import RGCanvasContent4Nodes from './RGCanvasContent4Nodes.svelte';
    import RGCanvasContent4Lines from './RGCanvasContent4Lines.svelte';
    import RGCanvasContent4FakeLines from './RGCanvasContent4FakeLines.svelte';
    import RGCanvasContent4CreatingLine from './RGCanvasContent4CreatingLine.svelte';

    // 定义与 Vue 版本一致的 Props
    export let showEasyView = false;
    export let creatingLine = false;
    export let defaultExpandHolderPosition = '';
    export let draggingNodeId = '';
    export let checkedNodeId = '';
    export let checkedLineId = '';
    export let defaultLineTextOnPath = false;
    export let graphInstanceId: string | undefined = undefined;

    onMount(() => {
        // console.log('[RGCanvasContent mounted]');
    });
</script>

<div class="rg-single-graph">
    <RGCanvasContent4Lines
            {showEasyView}
            {defaultLineTextOnPath}
            {checkedLineId}
            {graphInstanceId}
    >
        <svelte:fragment slot="line" let:lineConfig let:checked let:defaultLineTextOnPath let:graphInstanceId>
            <slot name="line" {lineConfig} {checked} {defaultLineTextOnPath} {graphInstanceId} />
        </svelte:fragment>
    </RGCanvasContent4Lines>

    <div class="rg-nodes-container-wrapper">
        {#if !showEasyView}
            <RGCanvasContent4Nodes
                    {defaultExpandHolderPosition}
                    {draggingNodeId}
                    {checkedNodeId}
            >
                <svelte:fragment slot="node" let:node let:checked let:dragging>
                    <slot name="node" {node} {checked} {dragging} />
                </svelte:fragment>
                <svelte:fragment slot="node-expand-button" let:node let:expandHolderPosition let:expandOrCollapseNode>
                    <slot
                            name="node-expand-button"
                            {node}
                            {expandHolderPosition}
                            {expandOrCollapseNode}
                    />
                </svelte:fragment>
            </RGCanvasContent4Nodes>
        {/if}
    </div>

    <RGCanvasContent4FakeLines
            {showEasyView}
            {defaultLineTextOnPath}
            {checkedLineId}
            {graphInstanceId}
    >
        <svelte:fragment slot="line" let:lineConfig let:checked let:defaultLineTextOnPath let:graphInstanceId>
            <slot name="line" {lineConfig} {checked} {defaultLineTextOnPath} {graphInstanceId} />
        </svelte:fragment>
    </RGCanvasContent4FakeLines>

    {#if creatingLine}
        <RGCanvasContent4CreatingLine
                {defaultLineTextOnPath}
                {graphInstanceId}
        >
            <svelte:fragment slot="line" let:lineConfig>
                <slot name="line" {lineConfig} />
            </svelte:fragment>
        </RGCanvasContent4CreatingLine>
    {/if}
</div>

// packages/platforms/react/src/relation-graph/src/core4react/RGCanvasContent.tsx
import React, {useMemo} from 'react';
import {RGLineSlotProps, RGNodeSlotProps} from '../../../../../../types';
import {RGNodeExpandHolderProps} from '../../../types-react';
import RGCanvasContent4Lines from "./RGCanvasContent4Lines";
import RGCanvasContent4Nodes from "./RGCanvasContent4Nodes";
import RGCanvasContent4FakeLines from "./RGCanvasContent4FakeLines";
import RGCanvasContent4CreatingLine from "./RGCanvasContent4CreatingLine";
import {useGraphInstance} from "../hooks/useGraphInstance";
import {useGraphStore} from "../hooks/useGraphStore";

export interface RGCanvasContentProps {
    nodeSlot?: React.FC<RGNodeSlotProps> | ((props: RGNodeSlotProps) => React.ReactNode)
    lineSlot?: React.FC<RGLineSlotProps> | ((props: RGLineSlotProps) => React.ReactNode)
    nodeExpandButtonSlot?: React.FC<RGNodeExpandHolderProps> | ((props: RGNodeExpandHolderProps) => React.ReactNode)
    showEasyView?: boolean
    creatingLine?: boolean
    defaultExpandHolderPosition?: string,
    draggingNodeId?: string,
    checkedNodeId?: string,
    checkedLineId?: string,
    defaultLineTextOnPath?: boolean,
    graphInstanceId?: string,
}

const RGCanvasContent: React.FC<RGCanvasContentProps> = (
    {
        nodeSlot,
        lineSlot,
        nodeExpandButtonSlot,
        showEasyView,
        creatingLine,
        defaultExpandHolderPosition,
        draggingNodeId,
        checkedNodeId,
        checkedLineId,
        graphInstanceId,
        defaultLineTextOnPath
    }
) => {
    const graphInstance = useGraphInstance();
    const {shouldRenderNodes, shouldRenderLines} = useGraphStore();
    const allNodeConfigList = useMemo(
        () => {
            if (showEasyView) {
                return [];
            }
            // console.log('shouldRenderNodes::useMemo::allNodeConfigList');
            return graphInstance.getShouldRenderNodes(shouldRenderNodes);
        },
        [graphInstance, shouldRenderNodes, showEasyView]);
    // const allNodeConfigList = graphInstance.getShouldRenderNodes(shouldRenderNodes);
    const allLineConfigList = useMemo(
        () => {
            if (showEasyView) {
                return [];
            }
            // console.log('shouldRenderLines::useMemo::shouldRenderLines');
            return graphInstance.getShouldRenderLines(shouldRenderLines);
        },
        [graphInstance, shouldRenderLines, showEasyView]);

    return (
        <div className="rg-single-graph">
            <RGCanvasContent4Lines
                graphInstanceId={graphInstanceId}
                showEasyView={showEasyView}
                defaultLineTextOnPath={defaultLineTextOnPath}
                checkedLineId={checkedLineId}
                lineSlot={lineSlot}
                allLineConfigList={allLineConfigList}
            />
            <div className="rg-nodes-container-wrapper">
                {!showEasyView && <RGCanvasContent4Nodes
                    defaultExpandHolderPosition={defaultExpandHolderPosition}
                    draggingNodeId={draggingNodeId}
                    checkedNodeId={checkedNodeId}
                    nodeSlot={nodeSlot}
                    nodeExpandButtonSlot={nodeExpandButtonSlot}
                    allNodeConfigList={allNodeConfigList}
                />}
            </div>
            <RGCanvasContent4FakeLines
                graphInstanceId={graphInstanceId}
                showEasyView={showEasyView}
                defaultLineTextOnPath={defaultLineTextOnPath}
                checkedLineId={checkedLineId}
                lineSlot={lineSlot}
            >
            </RGCanvasContent4FakeLines>
            {creatingLine && <RGCanvasContent4CreatingLine
                defaultLineTextOnPath={defaultLineTextOnPath}
                checkedLineId={checkedLineId}
                lineSlot={lineSlot}
            >
            </RGCanvasContent4CreatingLine>}
        </div>
    );
};

export default RGCanvasContent;
