// packages/platforms/svelte/src/core4svelte/RGCanvasContent4CreatingLine.svelte
<script lang="ts">
    import { useGraphInstance } from '../hooks/useGraphInstance';
    import { useGraphStore } from '../hooks/useGraphStore';
    import RGLineContent from './RGLineContent.svelte';

    export let defaultLineTextOnPath = false;
    export let graphInstanceId: string | undefined = undefined;

    const graphInstance = useGraphInstance();
    const { optionsStore } = useGraphStore();

    $: options = $optionsStore!;
    $: creatingLineConfig = graphInstance.generateCreatingLineConfig(options);
</script>

<div class="rg-lines-container rg-lines-container-el-lines">
    <div class="rg-linetext-container" />
    <svg class="rg-lines-svg rg-lines-svg-el-lines" xmlns="http://www.w3.org/2000/svg">
        <slot name="line" lineConfig={creatingLineConfig}>
            <RGLineContent lineConfig={creatingLineConfig} checked={false} {defaultLineTextOnPath} {graphInstanceId} />
        </slot>
    </svg>
</div>

// packages/platforms/react/src/relation-graph/src/core4react/RGCanvasContent4CreatingLine.tsx
import React from 'react';
import {
    RGLineSlotProps,
} from '../../../../../../types';
import RGLineContent from "./RGLineContent";
import {useGraphInstance} from "../hooks/useGraphInstance";
import {useGraphStore} from "../hooks/useGraphStore";

export interface RGCanvasContent4CreatingLineProps {
    lineSlot?: React.FC<RGLineSlotProps> | ((props: RGLineSlotProps) => React.ReactNode)
    defaultLineTextOnPath?: boolean,
    checkedLineId?: string,
    graphInstanceId?: string,
}

const RGCanvasContent4CreatingLine: React.FC<RGCanvasContent4CreatingLineProps> = (
    {
        lineSlot,
        defaultLineTextOnPath,
        graphInstanceId
    }
) => {
    const graphInstance = useGraphInstance();
    const {options} = useGraphStore();
    const creatingLineConfig = graphInstance.generateCreatingLineConfig(options);
    return (
        <div className="rg-lines-container rg-lines-container-el-lines">
            <div className="rg-linetext-container"/>
            <svg className="rg-lines-svg rg-lines-svg-el-lines"
                 xmlns="http://www.w3.org/2000/svg">
                {
                    lineSlot ?
                        lineSlot({lineConfig: creatingLineConfig})
                        : <RGLineContent
                            lineConfig={creatingLineConfig}
                            defaultLineTextOnPath={defaultLineTextOnPath}
                            graphInstanceId={graphInstanceId}
                        />
                }
            </svg>
        </div>
    );
};

export default RGCanvasContent4CreatingLine;
