// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGEasyView.vue
<script lang="ts" setup>
import { computed, onMounted, ref } from 'vue'
import { devLog } from '../../../../../../relation-graph-models/utils/RGCommon'
import {useGraphInstance} from "../hooks/useGraphInstance";
const graphInstance = useGraphInstance();
const $rgEasyCanvas = ref<HTMLCanvasElement>()
const options = computed(() => graphInstance.dataStores.optionsRef.value);
onMounted(() => {
  devLog('[RGEasyView mounted]');
    graphInstance.setEasyViewCanvas && graphInstance.setEasyViewCanvas($rgEasyCanvas.value!);
})
</script>
<template>
    <div class="rg-easy-view" :class="{'rg-easy-view-active':options.showEasyView}">
        <canvas ref="$rgEasyCanvas" style="width: 100%;height: 100%;" />
    </div>
</template>

// packages/platforms/react/src/relation-graph/src/core4react/RGEasyView.tsx
import React, {MutableRefObject, useEffect, useRef} from 'react';
import {RGCanvasProps} from './RGCanvas';
import { devLog } from '../../../../../../relation-graph-models/utils/RGCommon';
import {useGraphInstance} from "../hooks/useGraphInstance";
import {useGraphStore} from "../hooks/useGraphStore";

const RGCanvas: React.FC<RGCanvasProps> = (canvasProps) => {
  const graphInstance = useGraphInstance();
  const {options} = useGraphStore();
  const rgEasyCanvas$ = useRef() as MutableRefObject<HTMLCanvasElement>;

  useEffect(() => {
    devLog('[RGEasyView mounted]');
    graphInstance.setEasyViewCanvas(rgEasyCanvas$.current!);
    return () => {
        devLog('[RGEasyView UnMounted]');
    }
  }, []);

  return (
    <div className={`rg-easy-view ${options.showEasyView ? 'rg-easy-view-active' : ''}`}>
      <canvas ref={rgEasyCanvas$} />
    </div>
  );
};

export default RGCanvas;
