// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGLinePeel.vue
<script lang="ts" setup>
import {computed} from 'vue'
import {
    RGLinePeelProps,
} from '../../../../../../types';
import RGLineContent from "./RGLineContent.vue";
import {useGraphInstance} from "../hooks/useGraphInstance";

const {
    line,
    defaultLineTextOnPath,
    graphInstanceId,
    checked
} = defineProps<RGLinePeelProps>()
const graphInstance = useGraphInstance();

const config = computed(() => {
    return line.isFakeLine ? graphInstance.generateFakeLineConfig(line) : graphInstance.generateLineConfig(line);
})
</script>
<template>
    <g v-if="config">
        <slot
                name="line"
                :line-config="config"
                :defaultLineTextOnPath="defaultLineTextOnPath"
                :graph-instance-id="graphInstanceId"
                :checked="checked"
        >
            <RGLineContent
                    :line-config="config"
                    :defaultLineTextOnPath="defaultLineTextOnPath"
                    :graph-instance-id="graphInstanceId"
                    :checked="checked"
            />
        </slot>
    </g>
</template>

// packages/platforms/react/src/relation-graph/src/core4react/RGLinePeel.tsx
import React from 'react';
import {RGLine, RGFakeLine, RGLineSlotProps, RGLinePeelProps} from "../../../../../../types";
import RGLineContent from "./RGLineContent";
import {useAutoUpdateView, useGraphInstance} from "../hooks/useGraphInstance";

const RGLinePeel: React.FC<RGLinePeelProps & {
    lineSlot?: React.FC<RGLineSlotProps> | ((props: RGLineSlotProps) => React.ReactNode)
}> = (
    {
        line,
        defaultLineTextOnPath,
        graphInstanceId,
        checked,
        lineSlot
    }
) => {
    const graphInstance = useGraphInstance();
    useAutoUpdateView();
    const config = line.isFakeLine ? graphInstance.generateFakeLineConfig(line as RGFakeLine) : graphInstance.generateLineConfig(line as RGLine);
    return <>
        {config && (
            lineSlot ?
                lineSlot({lineConfig: config, defaultLineTextOnPath, graphInstanceId, checked})
                : <RGLineContent
                    lineConfig={config}
                    defaultLineTextOnPath={defaultLineTextOnPath}
                    graphInstanceId={graphInstanceId}
                    checked={checked}
                />
        )
        }
    </>;
};

export default RGLinePeel;
