// packages/platforms/vue2/src/core4vue/RGLinePeel.vue
<template>
    <g v-if="config">
        <slot
                name="line"
                :line-config="config"
                :defaultLineTextOnPath="defaultLineTextOnPath"
                :graph-instance-id="graphInstanceId"
                :checked="checked"
        >
            <RGLineContent
                    :line-config="config"
                    :defaultLineTextOnPath="defaultLineTextOnPath"
                    :graph-instance-id="graphInstanceId"
                    :checked="checked"
            />
        </slot>
    </g>
</template>

<script lang="ts">
import RGLineContent from "./RGLineContent.vue";

export default {
    name: 'RGLinePeel',
    components: {RGLineContent},
    props: [
        'line',
        'defaultLineTextOnPath',
        'graphInstanceId',
        'checked'
    ],
    data() {
        return {};
    },
    inject: ['graphStore'],
    computed: {
        graphInstance() {
            return this.graphStore.graphInstance;
        },
        config() {
            return this.line.isFakeLine ? this.graphInstance.generateFakeLineConfig(this.line) : this.graphInstance.generateLineConfig(this.line);
        }
    },
    watch: {},
    methods: {
        onLineClick(e) {
            this.graphInstance.onLineClick(this.lineConfig.line, e);
        }
    }
};
</script>

<style scoped>
</style>

// packages/platforms/react/src/relation-graph/src/core4react/RGLinePeel.tsx
import React from 'react';
import {RGLine, RGFakeLine, RGLineSlotProps, RGLinePeelProps} from "../../../../../../types";
import RGLineContent from "./RGLineContent";
import {useAutoUpdateView, useGraphInstance} from "../hooks/useGraphInstance";

const RGLinePeel: React.FC<RGLinePeelProps & {
    lineSlot?: React.FC<RGLineSlotProps> | ((props: RGLineSlotProps) => React.ReactNode)
}> = (
    {
        line,
        defaultLineTextOnPath,
        graphInstanceId,
        checked,
        lineSlot
    }
) => {
    const graphInstance = useGraphInstance();
    useAutoUpdateView();
    const config = line.isFakeLine ? graphInstance.generateFakeLineConfig(line as RGFakeLine) : graphInstance.generateLineConfig(line as RGLine);
    return <>
        {config && (
            lineSlot ?
                lineSlot({lineConfig: config, defaultLineTextOnPath, graphInstanceId, checked})
                : <RGLineContent
                    lineConfig={config}
                    defaultLineTextOnPath={defaultLineTextOnPath}
                    graphInstanceId={graphInstanceId}
                    checked={checked}
                />
        )
        }
    </>;
};

export default RGLinePeel;
