// packages/platforms/vue2/src/core4vue/RGNodeExpandHolder.vue
<template>
    <div :class="['rg-node-expand-holder', ('c-expand-positon-' + expandHolderPosition)]">
        <div
                class="rg-node-expand-button"
                :class="expandButtonClass"
                @click.stop="expandOrCollapseNode"
                @touchend.stop="expandOrCollapseNode"
        >
            <RGIcons v-if="node.expanded === false" iconName="icon-fangda" />
            <RGIcons v-else iconName="icon-suoxiao" />
        </div>
    </div>
</template>

<script lang="ts">
import RGIcons from "./widgets/RGIcons.vue";

export default {
    name: 'RGNodeExpandHolder',
    components: {RGIcons},
    props: {
        node: {
            type: Object,
            required: true
        },
        expandOrCollapseNode: {
            type: Function,
            required: true
        },
        expandHolderPosition: {
            type: String,
            required: true
        }
    },
    computed: {
        expandButtonClass() {
            return this.node.expanded === false ? 'c-expanded' : 'c-collapsed';
        }
    }
}
</script>

// packages/platforms/react/src/relation-graph/src/core4react/RGNodeExpandHolder.tsx
import React from 'react';
import {RGNodeExpandHolderProps} from "../../../types-react";
import RGIcons from "./widgets/RGIcons";

const RGNodeExpandHolder: React.FC<RGNodeExpandHolderProps> = ({node, expandOrCollapseNode, expandHolderPosition}) => {
  const expandButtonClass = node.expanded === false ? 'rg-node-expand-button c-expanded' : 'rg-node-expand-button c-collapsed';

  return (
    <div
      className={`rg-node-expand-holder c-expand-positon-${expandHolderPosition}`}
    >

      <div
        className={expandButtonClass}
        onClickCapture={expandOrCollapseNode}
        onTouchEnd={expandOrCollapseNode}
      >
        {node.expanded === false ? <RGIcons iconName="icon-fangda" /> : <RGIcons iconName="icon-suoxiao" />}
      </div>
    </div>
  );
};

export default RGNodeExpandHolder;
