// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGNodeExpandHolder.vue
<script lang="ts" setup>
import type {RGNode} from '../../../../../../types';
import {computed} from "vue";
import RGIcons from "./widgets/RGIcons.vue";

const props = defineProps<{
    node: RGNode
    expandOrCollapseNode: (e: MouseEvent) => void
    expandHolderPosition: string
}>();

const expandButtonClass = computed(() => {
    return props.node.expanded === false ? 'c-expanded' : 'c-collapsed'
})
</script>
<template>
    <div
            :class="['rg-node-expand-holder', ('c-expand-positon-'+expandHolderPosition)]"
    >
        <div
            class="rg-node-expand-button"
            :class="expandButtonClass"
            @click.stop="expandOrCollapseNode"
            @touchend.stop="expandOrCollapseNode"
        >
            <RGIcons v-if="node.expanded === false" iconName="icon-fangda" />
            <RGIcons v-else iconName="icon-suoxiao" />
        </div>
    </div>
</template>

// packages/platforms/react/src/relation-graph/src/core4react/RGNodeExpandHolder.tsx
import React from 'react';
import {RGNodeExpandHolderProps} from "../../../types-react";
import RGIcons from "./widgets/RGIcons";

const RGNodeExpandHolder: React.FC<RGNodeExpandHolderProps> = ({node, expandOrCollapseNode, expandHolderPosition}) => {
  const expandButtonClass = node.expanded === false ? 'rg-node-expand-button c-expanded' : 'rg-node-expand-button c-collapsed';

  return (
    <div
      className={`rg-node-expand-holder c-expand-positon-${expandHolderPosition}`}
    >

      <div
        className={expandButtonClass}
        onClickCapture={expandOrCollapseNode}
        onTouchEnd={expandOrCollapseNode}
      >
        {node.expanded === false ? <RGIcons iconName="icon-fangda" /> : <RGIcons iconName="icon-suoxiao" />}
      </div>
    </div>
  );
};

export default RGNodeExpandHolder;
