// packages/platforms/react/src/relation-graph/src/core4react/widgets/GraphLoading.tsx
import React from 'react';
import RGIcons from "./RGIcons";
import {useGraphInstance} from "../../hooks/useGraphInstance";
import {useGraphStore} from "../../hooks/useGraphStore";

const GraphLoading: React.FC = () => {
  const graphInstance = useGraphInstance();
  const {options} = useGraphStore();
  const clickGraphMask = (e) => {
    graphInstance.clearLoading();
  }
  return (
    <>
    {
      options && <div
    className={`rg-graph-loading ${!options.graphLoading ? 'rg-graph-loading-hide' : ''}`}
    onClick={(e) => {clickGraphMask(e);}}
  >
    <div className="rg-graph-loading-message">
      <RGIcons iconName="icon-lianjiezhong" className="rg-graph-loading-icon" />
        {options.graphLoadingText || 'Loading...'}
    </div>
  </div>
}
    </>
  );
};

export default GraphLoading;

// packages/platforms/vue3/src/relation-graph/src/core4vue3/widgets/GraphLoading.vue
<script lang="ts" setup>
import {computed} from "vue";
import {useGraphInstance} from "../../hooks/useGraphInstance";
import RGIcons from "./RGIcons.vue";

const graphInstance = useGraphInstance();
const options = computed(() => graphInstance.dataStores.optionsRef.value);
const clickGraphMask = (e) => {
    graphInstance.clearLoading();
}
</script>
<template>
    <div
            class="rg-graph-loading"
            :class="{'rg-graph-loading-hide': !options.graphLoading}"
            @click="clickGraphMask"
    >
        <div class="rg-graph-loading-message">
            <RGIcons icon-name="icon-lianjiezhong" class-name="rg-graph-loading-icon"/>
            {{ options.graphLoadingText || 'Loading...' }}
        </div>
    </div>
</template>
