// packages/platforms/svelte/src/core4svelte/widgets/GraphWatermark.svelte
<script lang="ts">
    import { onMount, onDestroy } from 'svelte';
    import { useGraphInstance } from '../../hooks/useGraphInstance';
    import type { RGWidgetPosition } from '../../../../../types';
    import {useGraphStore} from "../../hooks/useGraphStore";

    export let forImage = true;
    export let forDisplay = false;
    export let position: RGWidgetPosition = 'br';
    export let width: string | undefined = undefined;
    export let height: string | undefined = undefined;

    let watermarkRef: HTMLElement;

    const graphInstance = useGraphInstance();
    const {optionsStore} = useGraphStore();
    $: options = $optionsStore;

    $: show = (() => {
        let visible = false;
        if (options.snapshotting) {
            if (forImage === false) {
                visible = false;
            } else {
                visible = true;
            }
        } else {
            if (forDisplay === true) {
                visible = true;
            } else {
                visible = false;
            }
        }
        return visible;
    })();

    onMount(() => {
        if (watermarkRef) {
            graphInstance.setWatermarkDom(watermarkRef, forImage, forDisplay, position);
        }
    });

    onDestroy(() => {
        // 注意：Svelte 的 onDestroy 不接受参数，这里只是调用方法，不需要参数
        // 但 setWatermarkDom 需要参数来做清理判断
        graphInstance.setWatermarkDom(null, forImage, forDisplay, position);
    });
</script>

<div
        bind:this={watermarkRef}
        class="rg-watermark rg-watermark-{position || 'br'}"
        style:display={show ? '' : 'none'}
        style:--watermark-width={width}
        style:--watermark-height={height}
>
    <slot />
</div>

// packages/platforms/vue3/src/relation-graph/src/core4vue3/widgets/GraphWatermark.vue
<template>
    <div
            v-show="show"
            class="rg-watermark"
            :class="['rg-watermark-' + (position || 'br')]"
            ref="$watermarkRef"
            :style="{
                '--watermark-width': width,
                '--watermark-height': height
            }"
    >
        <slot/>
    </div>
</template>

<script lang="ts" setup>
import {computed, onMounted, onUnmounted, ref} from "vue";
import {RGWidgetPosition} from "../../../../types";
import {useGraphInstance} from "../../hooks/useGraphInstance";

const graphInstance = useGraphInstance();

const props = withDefaults(defineProps<{
    forImage?: boolean,
    forDisplay?: boolean,
    position?: RGWidgetPosition,
    width?: string,
    height?: string,
}>(), {
    forImage: true,
    forDisplay: false,
    position: 'br'
}); // RGWatermarkProps
const options = computed(() => graphInstance.dataStores.optionsRef.value);
const show = computed(() => {
    let visable = false;
    if (options.value.snapshotting) {
        if (props.forImage === false) {
            visable = false;
        } else {
            visable = true;
        }
    } else {
        if (props.forDisplay === true) {
            visable = true;
        } else {
            visable = false;
        }
    }
    ;
    return visable;
});
const $watermarkRef = ref();
onMounted(() => {
    graphInstance.setWatermarkDom($watermarkRef.value, props.forImage, props.forDisplay, props.position);
});
onUnmounted(() => {
    graphInstance.setWatermarkDom(null, props.forImage, props.forDisplay);
});
</script>
