// packages/platforms/react/src/relation-graph/src/core4react/widgets/GraphMoveOperator.tsx
import React from 'react';
import {useGraphInstance} from "../../hooks/useGraphInstance";

const GraphMoveOperator: React.FC = () => {
    const graphInstance = useGraphInstance();
    const canvasMoveMode = graphInstance?.options.canvasMoveMode || false;
    // Event handler for touchpad
    const onTouchpadMouseDown = (e: React.MouseEvent | React.TouchEvent) => {
        if (graphInstance) {
            graphInstance.startMoveCanvas(e.nativeEvent, true);
        }
    };
    return (
        <div
            className={`rg-move-operator ${canvasMoveMode ? 'rg-move-operator-active' : ''}`}
        >
            <div
                className="rg-move-touchpad"
                onMouseDown={onTouchpadMouseDown}
                onTouchStart={onTouchpadMouseDown}
            ></div>
        </div>
    )
};
export default GraphMoveOperator;

// packages/platforms/vue3/src/relation-graph/src/core4vue3/widgets/GraphMoveOperator.vue
<template>
    <div
            class="rg-move-operator"
            :class="{ 'rg-move-operator-active': canvasMoveMode }"
    >
        <div
                class="rg-move-touchpad"
                @mousedown="onTouchpadMouseDown"
                @touchstart="onTouchpadMouseDown"
        ></div>
    </div>
</template>

<script lang="ts" setup>
import {computed} from 'vue';
import {useGraphInstance} from "../../hooks/useGraphInstance";

const graphInstance = useGraphInstance();
const options = computed(() => graphInstance.dataStores.optionsRef.value);
const canvasMoveMode = computed(() => {
    return options.value.canvasMoveMode;
})
const onTouchpadMouseDown = (e: KeyboardEvent) => {
    graphInstance!.startMoveCanvas(e, true);
};
</script>
