// packages/platforms/svelte/src/core4svelte/widgets/GraphBackground.svelte
<script lang="ts">
    import { onMount, onDestroy } from 'svelte';
    import { useGraphInstance } from '../../hooks/useGraphInstance';
    import {useGraphStore} from "../../hooks/useGraphStore";

    export let forImage = true;
    export let forDisplay = true;

    let backgroundRef: HTMLElement;

    const graphInstance = useGraphInstance();
    const {optionsStore} = useGraphStore();
    $: options = $optionsStore;

    onMount(() => {
        if (backgroundRef) {
            graphInstance.setBackgroundDom(backgroundRef, forImage, forDisplay);
        }
    });

    onDestroy(() => {
        graphInstance.setBackgroundDom(null, forImage, forDisplay);
    });
</script>

<div
        bind:this={backgroundRef}
        class="rg-background"
        style:display={forDisplay !== false ? '' : 'none'}
>
    <slot />
</div>

// packages/platforms/vue3/src/relation-graph/src/core4vue3/widgets/GraphBackground.vue
<template>
    <div v-show="forDisplay!==false" class="rg-background" ref="$backgroundRef">
        <slot/>
    </div>
</template>

<script lang="ts" setup>
import {computed, onMounted, onUnmounted, ref} from "vue";
import {useGraphInstance} from "../../hooks/useGraphInstance";

const graphInstance = useGraphInstance();
const props = withDefaults(defineProps<{
    forImage?: boolean,
    forDisplay?: boolean
}>(), {
    forImage: true,
    forDisplay: true
}); // RGWatermarkProps
const options = computed(() => graphInstance.dataStores.optionsRef.value);
const $backgroundRef = ref();
onMounted(() => {
    graphInstance.setBackgroundDom($backgroundRef.value, props.forImage, props.forDisplay);
});
onUnmounted(() => {
    graphInstance.setBackgroundDom(null, props.forImage, props.forDisplay);
});
</script>
