// packages/platforms/svelte/src/core4svelte/RGCanvasContent4Nodes.svelte
<script lang="ts">
    import { useGraphInstance } from '../hooks/useGraphInstance';
    import { useGraphStore } from '../hooks/useGraphStore';
    import RGNodePeel from './RGNodePeel.svelte';

    export let defaultExpandHolderPosition = '';
    export let draggingNodeId = '';
    export let checkedNodeId = '';

    const graphInstance = useGraphInstance();
    const { shouldRenderNodesStore } = useGraphStore();

    $: shouldRenderNodes = $shouldRenderNodesStore!;
    $: allNodeConfigList = graphInstance.getShouldRenderNodes(shouldRenderNodes);
</script>

<div class="rg-nodes-container">
    {#each allNodeConfigList as thisNode (thisNode.id)}
        <RGNodePeel
                nodeProps={thisNode}
                {defaultExpandHolderPosition}
                dragging={thisNode.id === draggingNodeId}
                checked={thisNode.id === checkedNodeId}
        >
            <svelte:fragment slot="node" let:node let:checked let:dragging>
                <slot name="node" {node} {checked} {dragging} />
            </svelte:fragment>

            <svelte:fragment slot="node-expand-button" let:node let:expandHolderPosition let:expandOrCollapseNode>
                <slot
                        name="node-expand-button"
                        {node}
                        {expandHolderPosition}
                        {expandOrCollapseNode}
                />
            </svelte:fragment>
        </RGNodePeel>
    {/each}
</div>

// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGCanvasContent4Nodes.vue
<script lang="ts" setup>
import {computed, onMounted} from 'vue'
import {devLog} from '../../../../../../relation-graph-models/utils/RGCommon'
import RGNodePeel from './RGNodePeel.vue'
import {useGraphInstance} from "../hooks/useGraphInstance";
defineProps<{
    defaultExpandHolderPosition: string,
    draggingNodeId: string,
    checkedNodeId: string,
}>()
const graphInstance = useGraphInstance();
const allNodeConfigList = computed(() => {
    // console.error('allNodeConfigList: computed!')
    return graphInstance.getShouldRenderNodes(graphInstance.dataStores.shouldRenderNodesRef.value);
});
onMounted(() => {
    devLog('[RGCanvas mounted]')
})
</script>
<template>
    <div class="rg-nodes-container">
        <template v-for="thisNode in allNodeConfigList" :key="thisNode.id">
            <RGNodePeel
                    :node-props="thisNode"
                    :default-expand-holder-position="defaultExpandHolderPosition"
                    :dragging="thisNode.id===draggingNodeId"
                    :checked="thisNode.id===checkedNodeId"
            >
                <template #node="nodeSlotProps">
                    <slot v-bind="nodeSlotProps" name="node"/>
                </template>
                <template #node-expand-button="nodeExpandButtonSlotProps">
                    <slot name="node-expand-button" v-bind="nodeExpandButtonSlotProps" />
                </template>
            </RGNodePeel>
        </template>
    </div>
</template>
<style scoped>
</style>
