// packages/platforms/react/src/relation-graph/src/core4react/RGLineContent.tsx
import React, {useMemo} from 'react';
import {RGLinePathInfo, RGLineShape, RGLineSlotProps} from "../../../../../../types";
import RGLineText from "./RGLineText";
import RGLinePath from "./RGLinePath";
import {useGraphInstance} from "../hooks/useGraphInstance";

const RGLineContent: React.FC<RGLineSlotProps> = (
    {
        lineConfig,
        defaultLineTextOnPath,
        graphInstanceId,
        checked
    }
) => {
    const graphInstance = useGraphInstance();
    const linePathInfo = useMemo<RGLinePathInfo>(() => graphInstance.generateLinePath(lineConfig), [lineConfig]);
    const onLineClick = (e: React.MouseEvent | React.TouchEvent) => {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        graphInstance.onLineClick(lineConfig.line, e.nativeEvent);
    };
    const useTextOnPath = (lineConfig.line.useTextOnPath || defaultLineTextOnPath);
    const useSvgTextPath = useTextOnPath && (lineConfig.line.lineShape !== RGLineShape.StandardStraight);
    const showNormalLineText = !useSvgTextPath;
    const textStyle = graphInstance.generateLineTextStyle(lineConfig, linePathInfo);
    return (<>
        <RGLinePath
            lineConfig={lineConfig}
            linePathInfo={linePathInfo}
            onLineClick={onLineClick}
            useTextOnPath={useSvgTextPath}
            checked={checked}
            graphInstanceId={graphInstanceId}
        />
        {lineConfig.line.text && showNormalLineText && <RGLineText
            lineConfig={lineConfig}
            linePathInfo={linePathInfo}
            checked={checked}
        >
            {
                <div
                    className={`rg-line-label ${useTextOnPath ? 'rg-line-label-on-path':''}`}
                    style={{
                        ...textStyle.cssStyles
                    }}
                    onTouchStart={onLineClick}
                    onClick={onLineClick}
                >
                    {textStyle.text}
                </div>
            }
        </RGLineText>}
    </>);
};

export default RGLineContent;

// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGLineContent.vue
<script lang="ts" setup>
import {computed} from 'vue'
import {RGLineShape, RGLineSlotProps} from '../../../../../../types';
import RGLineText from "./RGLineText.vue";
import RGLinePath from "./RGLinePath.vue";
import {useGraphInstance} from "../hooks/useGraphInstance";
const graphInstance = useGraphInstance();
const {
    lineConfig,
    defaultLineTextOnPath,
    graphInstanceId,
    checked
} = defineProps<RGLineSlotProps>()
const linePathInfo = computed(() => {
    return graphInstance.generateLinePath(lineConfig)
});
const textStyle = computed(() => graphInstance.generateLineTextStyle(lineConfig, linePathInfo.value));
const useTextOnPath = computed(() => {
    return (lineConfig.line.useTextOnPath || defaultLineTextOnPath);
})
const useSvgTextPath = computed(() => {
    return useTextOnPath.value && (lineConfig.line.lineShape !== RGLineShape.StandardStraight);
})
const onLineClick = (e: MouseEvent | TouchEvent) => {
    graphInstance.onLineClick(lineConfig.line, e)
}
</script>
<template>
    <RGLinePath
            :lineConfig="lineConfig"
            :linePathInfo="linePathInfo"
            :useTextOnPath="useSvgTextPath"
            :graph-instance-id="graphInstanceId"
            :checked="checked"
            @onLineClick="onLineClick"
    />
    <RGLineText
            v-if="lineConfig.line.text && !useSvgTextPath"
            :lineConfig="lineConfig"
            :linePathInfo="linePathInfo"
            :checked="checked"
    >
        <div
                :class="`rg-line-label ${useTextOnPath ? 'rg-line-label-on-path':''}`"
                :style="{
                    ...textStyle.cssStyles
                }"
                @touchstart="onLineClick"
                @click="onLineClick"
        >
            {{ textStyle.text }}
        </div>
    </RGLineText>
</template>
