// packages/platforms/react/src/relation-graph/src/core4react/RGLinePath.tsx
import React, {PropsWithChildren} from 'react';
import {RGLinePathProps} from "../../../../../../types";
import {useGraphInstance} from "../hooks/useGraphInstance";

const RGLinePath: React.FC<PropsWithChildren<RGLinePathProps & {
    onLineClick: (e: React.MouseEvent | React.TouchEvent) => void,
}>> = ({lineConfig, linePathInfo, useTextOnPath, checked, graphInstanceId, onLineClick, children}) => {
    const graphInstance = useGraphInstance();
    const line = lineConfig.line;
    const selected = line.selected;
    const startArrowMarkerId = graphInstance.getArrowMarkerId(line, true);
    const endArrowMarkerId = graphInstance.getArrowMarkerId(line, false);
    const lineWidth = line.lineWidth ? (line.lineWidth + 'px') : undefined;
    const onPathTextStyle = useTextOnPath ? graphInstance.generateLineTextStyle4TextOnPath(lineConfig) : null;
    const pathId = graphInstanceId + '-' + line.id;
    return <g
        className={[
            'rg-line-peel',
            line.className,
            (checked && 'rg-line-checked'),
            (selected && 'rg-line-selected'),
            ((line.disablePointEvent || line.opacity === 0) && 'rg-line-disable-events'),
        ].filter(Boolean).join(' ')}
        data-id={line.id}
        style={{
            '--rg-line-width': lineWidth,
            '--rg-line-color': line.color,
            '--rg-line-opacity': line.opacity,
            '--rg-line-fontcolor': line.fontColor,
            '--rg-line-marker-end': endArrowMarkerId,
            '--rg-line-marker-start': startArrowMarkerId,
            ...(line.cssVars || {})
        }}
    >
        <path
            d={linePathInfo.pathData}
            className="rg-line-bg"
            onTouchStart={onLineClick}
            onClick={onLineClick}
        />
        <path
            id={pathId}
            d={linePathInfo.pathData}
            className={[
                'rg-line',
                line.dashType ? ('rg-line-dashtype-' + line.dashType) : undefined,
                line.animation ? ('rg-line-anm-' + line.animation) : undefined,
            ].filter(Boolean).join(' ')}
            // markerStart={startArrowMarkerId}
            // markerEnd={endArrowMarkerId}
        />
        {
            onPathTextStyle && <g>
                <text
                    className={`rg-line-text rg-line-text-on-path`}
                    dx={onPathTextStyle.textOffset.x + 'px'}
                    dy={onPathTextStyle.textOffset.y + 'px'}
                    onTouchStart={onLineClick}
                    onClick={onLineClick}
                >
                    <textPath xlinkHref={`#${pathId}`}
                              startOffset={onPathTextStyle.onPathStartOffset}
                              textAnchor={onPathTextStyle.textAnchor}
                              method="align"
                              spacing="auto"
                    >
                        {onPathTextStyle.text}
                    </textPath>
                </text>
            </g>
        }
        {children}
    </g>;
};
export default RGLinePath;

// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGLinePath.vue
<script lang="ts" setup>
import {computed} from 'vue'
import {RGLinePathProps} from '../../../../../../types';

import {useGraphInstance} from "../hooks/useGraphInstance";

const graphInstance = useGraphInstance();
const {lineConfig, linePathInfo, useTextOnPath, checked, graphInstanceId} = defineProps<RGLinePathProps>()
const emit = defineEmits<{
    (e: 'onLineClick', event: MouseEvent | TouchEvent): void;
}>()
const line = computed(() => {
    return lineConfig.line
})
const startArrowMarkerId = computed(() => {
    return graphInstance.getArrowMarkerId(lineConfig.line, true);
})
const endArrowMarkerId = computed(() => {
    return graphInstance.getArrowMarkerId(lineConfig.line, false);
})
const onPathTextStyle = computed(() => {
    return graphInstance.generateLineTextStyle4TextOnPath(lineConfig);
})
const lineWidth = computed(() => {
    return lineConfig.line.lineWidth ? (lineConfig.line.lineWidth + 'px') : undefined;
})
const pathId = computed(() => {
    return graphInstanceId + '-' +  lineConfig.line.id;
})
const onLineClick = (e: MouseEvent | TouchEvent) => {
    emit('onLineClick', e);
}
</script>
<template>
    <g
        :class="[
            'rg-line-peel',
            line.className,
            (line.selected && 'rg-line-selected'),
            ((line.disablePointEvent || line.opacity === 0) && 'rg-line-disable-events'),
            (checked && 'rg-line-checked')
          ]"
        :data-id="line.id"
        :style="{
            '--rg-line-width': lineWidth,
            '--rg-line-color': line.color,
            '--rg-line-opacity': line.opacity,
            '--rg-line-fontcolor': line.fontColor,
            '--rg-line-marker-end': endArrowMarkerId,
            '--rg-line-marker-start': startArrowMarkerId,
            ...(line.cssVars || {})
        }"
    >
        <path
                :d="linePathInfo.pathData"
                class="rg-line-bg"
                @touchstart="onLineClick"
                @click="onLineClick"
        />
        <path
                :id="pathId"
                :d="linePathInfo.pathData"
                class="rg-line"
                :class="[
                    line.dashType ? ('rg-line-dashtype-' + line.dashType) : undefined,
                    line.animation ? ('rg-line-anm-' + line.animation) : undefined,
                ]"
        />
        <g
                v-if="
                useTextOnPath &&
                onPathTextStyle
              "
        >
            <text
                    class="rg-line-text rg-line-text-on-path"
                    :dx="onPathTextStyle.textOffset.x + 'px'"
                    :dy="onPathTextStyle.textOffset.y + 'px'"
                    @touchstart="onLineClick"
                    @click="onLineClick"
            >
                <textPath :xlink:href="'#'+pathId"
                          :startOffset="onPathTextStyle.onPathStartOffset"
                          :text-anchor="onPathTextStyle.textAnchor"
                          method="align"
                          spacing="auto"> {{ onPathTextStyle.text }} </textPath>
            </text>
        </g>
        <slot />
    </g>
</template>
