// packages/platforms/react/src/relation-graph/src/core4react/RGLineText.tsx
import React, {PropsWithChildren} from 'react';
import {createPortal} from "react-dom";
import {RGLineTextProps} from "../../../../../../types";
import {useGraphInstance} from "../hooks/useGraphInstance";

const RGLineText: React.FC<PropsWithChildren<RGLineTextProps>> = ({children, lineConfig, checked}) => {
    const graphInstance = useGraphInstance();
    if (!graphInstance) return null;
    const lineTextContainer = graphInstance.getLineTextContainer(lineConfig?.line);
    if (!lineTextContainer) return null;
    const line = lineConfig.line;
    const selected = line.selected;
    return createPortal(<div
        className={[
            'rg-line-peel',
            line.className,
            (checked && 'rg-line-checked'),
            ((line.disablePointEvent || line.opacity === 0) && 'rg-line-disable-events'),
            (selected && 'rg-line-selected')
        ].filter(Boolean).join(' ')}
        data-id={line.id}
        style={{
            '--rg-line-color': line.color,
            '--rg-line-fontsize': (lineConfig.line.fontSize ? `${lineConfig.line.fontSize}px` : undefined),
            '--rg-line-opacity': line.opacity,
            '--rg-line-fontcolor': line.fontColor,
            ...(line.cssVars || {})
        }}
    >
        {children}
    </div>, lineTextContainer);
};
export default RGLineText;

// packages/platforms/vue3/src/relation-graph/src/core4vue3/RGLineText.vue
<script lang="ts" setup>
import {computed} from 'vue'
import {RGLineTextProps} from "../../../../../../types";
import {useGraphInstance} from "../hooks/useGraphInstance";

const graphInstance = useGraphInstance();
const {lineConfig, checked} = defineProps<RGLineTextProps>();
const line = computed(() => {
    return lineConfig?.line;
})
const lineTextContainer = computed(() => {
    if (line.value.isFakeLine) {
        return graphInstance.dataStores.textContainer4FakeLineRef.value;
    } else {
        return graphInstance.dataStores.textContainer4NormalRef.value;
    }
})
</script>
<template>
    <foreignObject v-if="line && lineTextContainer">
        <teleport :to="lineTextContainer">
            <div :class="[
                    'rg-line-peel',
                    line.className,
                    (checked && 'rg-line-checked'),
                    ((line.disablePointEvent || line.opacity === 0) && 'rg-line-disable-events'),
                    (line.selected && 'rg-line-selected')
                ]"
                :data-id="line.id"
                :style="{
                    '--rg-line-color': line.color,
                    '--rg-line-fontsize': (line.fontSize ? `${line.fontSize}px` : undefined),
                    '--rg-line-opacity': line.opacity,
                    '--rg-line-fontcolor': line.fontColor,
                    ...(line.cssVars || {})
                }"
            >
                <slot />
            </div>
        </teleport>
    </foreignObject>
    <g v-else>
        <text>Null-text-{{!!line}}-{{!!lineTextContainer}}</text>
    </g>
</template>
