// packages/platforms/react/src/relation-graph/src/core4react/editing/RGConnectSource.tsx
import React, {PropsWithChildren} from 'react';
import {RGConnectSourceProps} from '../../../../../../../types';
import {useGraphInstance} from "../../hooks/useGraphInstance";

const RGConnectSource:React.FC<PropsWithChildren<RGConnectSourceProps>> = ({ lineTemplate, onConnectStart, onConnectEnd, children, className, style }) => {
  const graphInstance = useGraphInstance();

  const onMouseDown = ($event: React.MouseEvent) => {
    onConnectStart && onConnectStart(lineTemplate, $event.nativeEvent);
    $event.stopPropagation();
    graphInstance.startCreateLineFromNode(null, lineTemplate, $event.nativeEvent, (from, to, newLine) => {
      onConnectEnd && onConnectEnd(from, to, newLine);
      graphInstance.defaultLineConnectEndHandler(from, to, newLine);
    });
  };
  return (
    <div
      className={`rg-connect-source-handle ${className || ''}`}
      style={style}
      onMouseDown={(event) => onMouseDown(event)}
      onClick={(event) => { event.stopPropagation(); }}
    >
      {children}
    </div>
  );
};

export default RGConnectSource;

// packages/platforms/vue3/src/relation-graph/src/core4vue3/editing/RGConnectSource.vue
<template>
    <div
            class="rg-connect-source-handle"
            :class="[
                'rg-connect-ctl-handler',
                'rg-connect-target',
                $attrs.className,
            ]"
            :style="$attrs.style"
            @mousedown="onMouseDown($event)"
            @click="onClick"
    >
        <slot/>
    </div>
</template>

<script lang="ts" setup>

import {
    JsonLine,
    JsonLineLike,
    JsonLineTemplate,
    RGLineTarget,
    RGNode,
    RGPosition,
    RGUserEvent
} from "../../../../types";
import {useGraphInstance} from "../../hooks/useGraphInstance";
const graphInstance = useGraphInstance();

const props = defineProps<{
    lineTemplate: JsonLineTemplate;
}>();
const emit = defineEmits<{
    onConnectStart: [newLineTemplate?:JsonLineLike, event?:RGUserEvent]
    onLineConnectEnd: [fromNode:RGNode|RGLineTarget, toNode:RGNode|RGLineTarget|RGPosition, newLineJson?:JsonLine]
}>();
const onClick = ($event: RGUserEvent) => {
    $event.stopPropagation();
}
const onMouseDown = ($event: RGUserEvent) => {
    $event.stopPropagation();
    emit('onConnectStart', props.lineTemplate, $event);
    graphInstance.startCreateLineFromNode(null, props.lineTemplate || {}, $event, (fromNode:RGNode|RGLineTarget, toNode:RGNode|RGLineTarget|RGPosition, newLineJson?:JsonLine) => {
        emit('onLineConnectEnd', fromNode, toNode, newLineJson);
        graphInstance.defaultLineConnectEndHandler(fromNode, toNode, newLineJson);
    });
}
</script>

<style scoped>
</style>
