// packages/platforms/react/src/relation-graph/src/core4react/editing/RGEditingNearNodeWidget.tsx
import React, {PropsWithChildren} from 'react';
import {RGWidgetPosition, RGWidgetProps} from '../../../../../../../types';

const RGEditingNearNodeWidget: React.FC<PropsWithChildren<RGWidgetProps>> = ({ position, children }) => {
  const _position: RGWidgetPosition = position || 'top';
  return (
    <div
      className={`rg-editing-bar rg-editing-bar-${_position}`}
    >
      {children}
    </div>
  );
};

export default RGEditingNearNodeWidget;

// packages/platforms/vue3/src/relation-graph/src/core4vue3/editing/RGEditingNearNodeWidget.vue
<template>
    <div
            class="rg-editing-bar"
            :class="['rg-editing-bar-' + (position || 'top')]"
    >
        <slot/>
    </div>
</template>

<script lang="ts" setup>
import {RGWidgetPosition} from "../../../../types";

const props = defineProps<{
    position?: RGWidgetPosition
}>();
</script>
