// packages/platforms/react/src/relation-graph/src/core4react/editing/RGEditingResize.tsx
import React from 'react';
import {RGResizeHandlePosition} from "../../../../../../../types";
import {useGraphInstance} from "../../hooks/useGraphInstance";
import {useGraphStore} from "../../hooks/useGraphStore";

const RGEditingResize: React.FC<{
    disableResizeWidth?: boolean,
    disableResizeHeight?: boolean,
    beforeResizeStart?: () => void;
}> = ({disableResizeWidth, disableResizeHeight, beforeResizeStart}) => {
    const graphInstance = useGraphInstance();
    const {options} = useGraphStore();

    const onMouseDown = (type: RGResizeHandlePosition, event: React.MouseEvent) => {
        event.stopPropagation();
        beforeResizeStart && beforeResizeStart();
        graphInstance.onResizeStart(type, event.nativeEvent);
    };

    return (
        <div className="rg-resize-ctl">
            {options.editingController.width > 30 && (!disableResizeWidth && !disableResizeHeight) && (
                <div
                    className="rg-resize-ctl-handler rg-resize-ctl-tl"
                    onMouseDown={(event) => onMouseDown('tl', event)}
                ></div>
            )}
            {options.editingController.width > 30 && (!disableResizeWidth && !disableResizeHeight) && (
                <div
                    className="rg-resize-ctl-handler rg-resize-ctl-tr"
                    onMouseDown={(event) => onMouseDown('tr', event)}
                ></div>
            )}
            {options.editingController.width > 30 && (!disableResizeWidth && !disableResizeHeight) && (
                <div
                    className="rg-resize-ctl-handler rg-resize-ctl-bl"
                    onMouseDown={(event) => onMouseDown('bl', event)}
                ></div>
            )}
            {(!disableResizeWidth && !disableResizeHeight) && <div
                className="rg-resize-ctl-handler rg-resize-ctl-br"
                onMouseDown={(event) => onMouseDown('br', event)}
            ></div>}
            {(options.editingController.width > 60 || (disableResizeWidth)) && (!disableResizeHeight) && (
                <div
                    className="rg-resize-ctl-handler rg-resize-ctl-t"
                    onMouseDown={(event) => onMouseDown('t', event)}
                ></div>
            )}
            {(options.editingController.width > 60 || (disableResizeWidth)) && (!disableResizeHeight) && (
                <div
                    className="rg-resize-ctl-handler rg-resize-ctl-b"
                    onMouseDown={(event) => onMouseDown('b', event)}
                ></div>
            )}
            {(options.editingController.height > 60 || (disableResizeHeight)) && (!disableResizeWidth) && (
                <div
                    className="rg-resize-ctl-handler rg-resize-ctl-l"
                    onMouseDown={(event) => onMouseDown('l', event)}
                ></div>
            )}
            {(options.editingController.height > 60 || (disableResizeHeight)) && (!disableResizeWidth) && (
                <div
                    className="rg-resize-ctl-handler rg-resize-ctl-r"
                    onMouseDown={(event) => onMouseDown('r', event)}
                ></div>
            )}
        </div>
    );
};

export default RGEditingResize;

// packages/platforms/vue3/src/relation-graph/src/core4vue3/editing/RGEditingResize.vue
<template>
    <div class="rg-resize-ctl">
        <div v-if="options.editingController.width > 30 && (!disableResizeWidth && !disableResizeHeight)" class="rg-resize-ctl-handler rg-resize-ctl-tl"
             @mousedown="onMouseDown('tl', $event)"></div>
        <div v-if="options.editingController.width > 30 && (!disableResizeWidth && !disableResizeHeight)" class="rg-resize-ctl-handler rg-resize-ctl-tr"
             @mousedown="onMouseDown('tr', $event)"></div>
        <div v-if="options.editingController.width > 30 && (!disableResizeWidth && !disableResizeHeight)" class="rg-resize-ctl-handler rg-resize-ctl-bl"
             @mousedown="onMouseDown('bl', $event)"></div>
        <div v-if="(!disableResizeWidth && !disableResizeHeight)" class="rg-resize-ctl-handler rg-resize-ctl-br" @mousedown="onMouseDown('br', $event)"></div>
        <div v-if="(options.editingController.width > 60 || (disableResizeWidth)) && (!disableResizeHeight)" class="rg-resize-ctl-handler rg-resize-ctl-t"
             @mousedown="onMouseDown('t', $event)"></div>
        <div v-if="(options.editingController.width > 60 || (disableResizeWidth)) && (!disableResizeHeight)" class="rg-resize-ctl-handler rg-resize-ctl-b"
             @mousedown="onMouseDown('b', $event)"></div>
        <div v-if="(options.editingController.height > 60 || (disableResizeHeight)) && (!disableResizeWidth)" class="rg-resize-ctl-handler rg-resize-ctl-l"
             @mousedown="onMouseDown('l', $event)"></div>
        <div v-if="(options.editingController.height > 60 || (disableResizeHeight)) && (!disableResizeWidth)" class="rg-resize-ctl-handler rg-resize-ctl-r"
             @mousedown="onMouseDown('r', $event)"></div>
    </div>
</template>

<script lang="ts" setup>
import {
    RGResizeHandlePosition,
    RGUserEvent,
} from "../../../../types";
import {computed} from "vue";
import {useGraphInstance} from "../../hooks/useGraphInstance";

const graphInstance = useGraphInstance();
const props = defineProps<{
    disableResizeWidth?: boolean,
    disableResizeHeight?: boolean,
}>();

const emit = defineEmits<{
    (e: 'beforeResizeStart'):void;
}>();
const options = computed(() => graphInstance.dataStores.optionsRef.value);
const onMouseDown = (type: RGResizeHandlePosition, $event: RGUserEvent) => {
    $event.stopPropagation();
    emit('beforeResizeStart');
    graphInstance.onResizeStart(type, $event);
}
</script>
