// packages/platforms/vue3/src/relation-graph/src/core4vue3/editing/RGConnectTarget.vue
<template>
    <g
        v-if="forSvg"
            ref="targetRef"
            :class="[
                'rg-connect-ctl-handler',
                'rg-connect-target',
                attrs.className,
            ]"
            :style="attrs.style"
            :data-point="actualJunctionPoint"
            @mousedown="onMouseDown"
            @mouseup="onMouseUp(actualJunctionPoint, $event)"
            @click="onClick"
    >
        <slot />
    </g>
    <div
        v-else
            ref="targetRef"
            :class="[
                'rg-connect-ctl-handler',
                'rg-connect-target',
                attrs.className,
            ]"
            :style="hostStyle"
            :data-point="actualJunctionPoint"
            @mousedown="onMouseDown"
            @mouseup="onMouseUp(actualJunctionPoint, $event)"
            @click="onClick"
    >
        <slot />
    </div>
</template>

<script lang="ts" setup>
import {
    JsonLine,
    JsonLineLike, JsonLineTemplate,
    RGConnectTargetDomMode,
    RGInnerConnectTargetType,
    RGJunctionPoint, RGLineTarget,
    RGNode,
    RGPosition,
    RGUserEvent
} from "../../../../types";
import {computed, onMounted, onUnmounted, ref, useAttrs, watch} from "vue";
import {useGraphInstance} from "../../hooks/useGraphInstance";
const graphInstance = useGraphInstance();
const attrs = useAttrs();

const props = defineProps<{
    junctionPoint?: RGJunctionPoint;
    targetId: string;
    targetType?: string;
    targetData?: any;
    lineTemplate?: JsonLineTemplate;
    disableDrop?: boolean;
    disableDrag?: boolean;
    forSvg?: boolean;
    domMode?: RGConnectTargetDomMode;
    measureSelector?: string;
    strictMeasureTarget?: boolean;
}>();
const emit = defineEmits<{
    onLineVertexBeDropped: [fromNode:RGNode|RGLineTarget|RGPosition, toNode:RGNode|RGLineTarget|RGPosition, newLineJson?:JsonLine]
    onDragConnectStart: [newLineTemplate:JsonLineLike, event:RGUserEvent]
    onDragConnectEnd: [fromNode:RGNode|RGLineTarget|RGPosition, toNode:RGNode|RGLineTarget|RGPosition, newLineJson?:JsonLine]
}>();
const targetRef = ref();
const actualJunctionPoint = computed(() => props.junctionPoint || RGJunctionPoint.border);
const normalizedDomMode = computed<RGConnectTargetDomMode>(() => (!props.forSvg && props.domMode === 'contents') ? 'contents' : 'wrap');
const hostStyle = computed(() => normalizedDomMode.value === 'contents' ? [attrs.style as any, {display: 'contents'}] : attrs.style);
const registerTarget = () => {
    if (!targetRef.value) {
        return;
    }
    graphInstance.registerConnectTarget({
        hostEl: targetRef.value,
        targetId: props.targetId,
        targetType: props.targetType || RGInnerConnectTargetType.NodePoint,
        junctionPoint: actualJunctionPoint.value,
        targetData: props.targetData,
        domMode: normalizedDomMode.value,
        measureSelector: props.measureSelector,
        strictMeasureTarget: props.strictMeasureTarget
    });
};
onMounted(() => {
    registerTarget();
});
watch(() => [props.targetId, props.targetType, props.junctionPoint, props.targetData, props.domMode, props.measureSelector, props.strictMeasureTarget, props.forSvg], ([targetId], oldValue) => {
    const oldTargetId = oldValue?.[0];
    if (oldTargetId && oldTargetId !== targetId) {
        graphInstance.unregisterConnectTarget(oldTargetId);
    }
    registerTarget();
}, {
    deep: true
});
onUnmounted(() => {
    graphInstance.unregisterConnectTarget(props.targetId);
});
const onClick = ($event: RGUserEvent) => {
    $event.stopPropagation();
}
const onMouseUp = (type: RGJunctionPoint, event: MouseEvent | TouchEvent) => {
    event.stopPropagation();
    if (props.disableDrop) {
        return;
    }
    graphInstance.onLineVertexBeDropped(type, event, undefined, (fromNode:RGNode, toNode:RGNode|RGPosition, newLineJson:JsonLine) => {
        emit('onLineVertexBeDropped', fromNode, toNode, newLineJson);
    });
};
const onMouseDown = ($event: MouseEvent) => {
    $event.stopPropagation();
    if (props.disableDrag) {
        return;
    }
    if (graphInstance.options.creatingLinePlot) {
        return;
    }
    const newLineJson: JsonLineTemplate = Object.assign({}, props.lineTemplate || {});
    const actualTargetType = graphInstance.getConnectTargetById(props.targetId)?.targetType || props.targetType || RGInnerConnectTargetType.NodePoint;
    if (!newLineJson.from) {
        newLineJson.from = props.targetId;
    }
    if (!newLineJson.fromType) {
        newLineJson.fromType = actualTargetType;
    }
    if (!newLineJson.fromJunctionPoint) {
        newLineJson.fromJunctionPoint = actualJunctionPoint.value;
    }
    emit('onDragConnectStart', newLineJson, $event);
    graphInstance.startCreateLineFromNode(null, newLineJson, $event, (from, to, newLine) => {
        emit('onDragConnectEnd', from, to, newLine);
    });
};
</script>

<style scoped>
</style>

// packages/platforms/react/src/relation-graph/src/core4react/editing/RGConnectTarget.tsx
import React, {PropsWithChildren, useEffect, useRef} from 'react';
import {
    RGConnectTargetProps,
    RGInnerConnectTargetType,
    RGJunctionPoint
} from "../../../../../../../types";
import {useGraphInstance} from "../../hooks/useGraphInstance";

const RGConnectTarget: React.FC<PropsWithChildren<RGConnectTargetProps>> = ({
                                                             children,
                                                             className,
                                                             style,
                                                             forSvg,
                                                             domMode,
                                                             measureSelector,
                                                             strictMeasureTarget,
                                                             junctionPoint, targetId, targetType, targetData,
                                                             lineTemplate,
                                                             disableDrop, disableDrag,
                                                             onLineVertexBeDropped,
                                                             onDragConnectStart,
                                                         onDragConnectEnd
                                                         }) => {
    const graphInstance = useGraphInstance();
    const targetRef = useRef<SVGGElement | HTMLDivElement | null>(null);
    const actualJunctionPoint = junctionPoint || RGJunctionPoint.border;
    const normalizedDomMode = !forSvg && domMode === 'contents' ? 'contents' : 'wrap';
    const hostStyle = !forSvg && normalizedDomMode === 'contents' ? {
        ...(style || {}),
        display: 'contents'
    } : style;
    const setTargetRef = (element: SVGGElement | HTMLDivElement | null) => {
        targetRef.current = element;
    };
    useEffect(() => {
        if (!targetRef.current) {
            return;
        }
        graphInstance.registerConnectTarget({
            hostEl: targetRef.current,
            targetId,
            targetType: targetType || RGInnerConnectTargetType.CanvasPoint,
            junctionPoint: actualJunctionPoint,
            targetData,
            domMode: normalizedDomMode,
            measureSelector,
            strictMeasureTarget
        });
    }, [actualJunctionPoint, graphInstance, measureSelector, normalizedDomMode, strictMeasureTarget, targetData, targetId, targetType]);
    useEffect(() => {
        return () => {
            graphInstance.unregisterConnectTarget(targetId);
        }
    }, [graphInstance, targetId]);
    const onMouseUp = (type: RGJunctionPoint, event: React.MouseEvent) => {
        event.stopPropagation();
        if (disableDrop) {
            return;
        }
        graphInstance.onLineVertexBeDropped(type, event.nativeEvent, undefined, (fromNode, toNode, newLineJson) => {
            onLineVertexBeDropped && onLineVertexBeDropped(fromNode, toNode, newLineJson);
        });
    };
    const onMouseDown = ($event: React.MouseEvent) => {
        $event.stopPropagation();
        if (disableDrag) {
            return;
        }
        if (graphInstance.options.creatingLinePlot) {
            return;
        }
        const newLineJson = Object.assign({}, lineTemplate || {});
        const actualTargetType = graphInstance.getConnectTargetById(targetId)?.targetType || targetType || RGInnerConnectTargetType.NodePoint;
        if (!newLineJson.from) {
            newLineJson.from = targetId;
        }
        if (!newLineJson.fromType) {
            newLineJson.fromType = actualTargetType;
        }
        if (!newLineJson.fromJunctionPoint) {
            newLineJson.fromJunctionPoint = actualJunctionPoint;
        }
        onDragConnectStart && onDragConnectStart(newLineJson, $event.nativeEvent);
        graphInstance.startCreateLineFromNode(null, newLineJson, $event.nativeEvent, (from, to, newLine) => {
            onDragConnectEnd && onDragConnectEnd(from, to, newLine);
        });
    };
    return (
        forSvg ?
            <g
                ref={setTargetRef as React.Ref<SVGGElement>}
                className={`rg-connect-ctl-handler rg-connect-target ${className || ''}`}
                style={style}
                data-point={actualJunctionPoint}
                onMouseDown={(event) => onMouseDown(event)}
                onMouseUp={(event) => onMouseUp(actualJunctionPoint, event)}
                onClick={(event) => {
                    event.stopPropagation();
                }}
            >
                {children}
            </g>
            :
        <div
            ref={setTargetRef as React.Ref<HTMLDivElement>}
            className={`rg-connect-ctl-handler rg-connect-target ${className || ''}`}
            style={hostStyle}
            data-point={actualJunctionPoint}
            onMouseDown={(event) => onMouseDown(event)}
            onMouseUp={(event) => onMouseUp(actualJunctionPoint, event)}
            onClick={(event) => {
                event.stopPropagation();
            }}
        >
            {children}
        </div>
    );
};

export default RGConnectTarget;
