// packages/platforms/vue3/src/relation-graph/src/core4vue3/editing/RGEditingNodeController.vue
<template>
    <div
            v-if="options.editingController.show"
            class="rg-editing-ctrl"
            :class="{ 'rg-ctrl-hide-border': props.hideBorderForSingleNode && options.editingController.nodes.length === 1 }"
            :style="{
              width: options.editingController.width + 'px',
              height: options.editingController.height + 'px',
              transform: `translate(${options.editingController.x}px, ${options.editingController.y}px)`
            }"
    >
        <slot/>
    </div>
</template>

<script lang="ts" setup>
import {computed} from "vue";
import {useGraphInstance} from "../../hooks/useGraphInstance";

const props = withDefaults(defineProps<{
    hideBorderForSingleNode?: boolean
}>(), {
    hideBorderForSingleNode: false
});

const graphInstance = useGraphInstance();

const options = computed(() => graphInstance.dataStores.optionsRef.value);

</script>

<style scoped>
</style>

// packages/platforms/react/src/relation-graph/src/core4react/editing/RGEditingNodeController.tsx
import React, {PropsWithChildren} from 'react';
import {useGraphStore} from "../../hooks/useGraphStore";

const RGEditingNodeController:React.FC<PropsWithChildren<{
    hideBorderForSingleNode?: boolean
}>> = ({ children, hideBorderForSingleNode }) => {
  const {options} = useGraphStore();

  if (!options.editingController.show) {
    return null;
  }
  const style = {
    width: options.editingController.width + 'px',
    height: options.editingController.height + 'px',
    transform: `translate(${options.editingController.x}px, ${options.editingController.y}px)`
  };
  return (
    <div className={`rg-editing-ctrl ${hideBorderForSingleNode && options.editingController.nodes.length === 1 ? 'rg-ctrl-hide-border':''}`} style={style}>
      {children}
    </div>
  );
};

export default RGEditingNodeController;
