// packages/platforms/vue3/src/relation-graph/src/core4vue3/editing/RGMiniView.vue
<template>
    <div
            class="rg-miniview"
            :class="[
                    'rg-miniview-' + (position || 'br'),
                    $attrs.className
                    ]"
            ref="$rgMiniView"
            :style="{
                ...$attrs.style,
                '--miniview-width': width,
                '--miniview-height': height
            }"
    >
        <div class="rg-miniview-container">
            <canvas
                    ref="$rgMiniViewCanvas"
                    :class="{
                        'rg-mv-canvas-reset': options.miniViewVisibleHandle.emptyContent
                    }"
                    @click="onClickCanvas"
            />
            <div
                    class="rg-mv-visible-area"
                    @mousedown="onMouseDown"
                    :style="{
                        transform: `translate(${options.miniViewVisibleHandle.x}px, ${options.miniViewVisibleHandle.y}px)`,
                        // left: `${options.miniViewVisibleHandle.x}px`,
                        // top: `${options.miniViewVisibleHandle.y}px`,
                        width: options.miniViewVisibleHandle.width + 'px',
                        height: options.miniViewVisibleHandle.height + 'px'
                    }"
            ></div>
        </div>
    </div>
</template>

<script lang="ts" setup>
import {RGUserEvent, RGWidgetPosition} from "../../../../types";
import {computed, onMounted, onUnmounted, ref} from "vue";
import {useGraphInstance} from "../../hooks/useGraphInstance";

const graphInstance = useGraphInstance();
const options = computed(() => graphInstance.dataStores.optionsRef.value);
const props = defineProps<{
    position?: RGWidgetPosition,
    width?: string,
    height?: string,
    className?: string
}>(); // RGMiniViewProps
const $rgMiniView = ref<HTMLDivElement>();
const $rgMiniViewCanvas = ref<HTMLCanvasElement>();
onMounted(() => {
    graphInstance.onMiniViewMounted();
    graphInstance.setMiniViewCanvas($rgMiniViewCanvas.value!);
});
onUnmounted(() => {
    graphInstance.onMiniViewUnMounted();
});
const onMouseDown = (e: RGUserEvent) => {
    graphInstance.onVisibleViewHandleDragStart(e);
}
const onClickCanvas = (e: RGUserEvent) => {
    graphInstance.resetByVisiableView(e);
}
</script>

// packages/platforms/react/src/relation-graph/src/core4react/editing/RGMiniView.tsx
import React, {useEffect, useRef} from 'react';
import {RGMiniViewProps} from "../../../../../../../types";
import {useAutoUpdateView, useGraphInstance} from "../../hooks/useGraphInstance";
import {useGraphStore} from "../../hooks/useGraphStore";

const RGMiniView: React.FC<RGMiniViewProps> = ({className, style, position = 'br', width, height}) => {
    const graphInstance = useGraphInstance();
    useAutoUpdateView();
    const {options} = useGraphStore();
    const $rgMiniView = useRef<HTMLDivElement>(null);
    const $rgMiniViewCanvas = useRef<HTMLCanvasElement>(null);

    useEffect(() => {
        graphInstance.onMiniViewMounted();
        graphInstance.setMiniViewCanvas($rgMiniViewCanvas.current!);

        return () => {
            graphInstance.onMiniViewUnMounted();
        };
    }, []);

    const onMouseDown = (e: React.MouseEvent) => {
        graphInstance.onVisibleViewHandleDragStart(e.nativeEvent);
    };

    const onClickCanvas = async (e: React.MouseEvent) => {
        graphInstance.resetByVisiableView(e.nativeEvent);
    };

    return (
        <div
            className={`rg-miniview rg-miniview-${position} ${className || ''}`}
            ref={$rgMiniView}
            style={{
                ...style,
                '--miniview-width': width,
                '--miniview-height': height
            }}
        >
            <div className="rg-miniview-container">
                <canvas
                    ref={$rgMiniViewCanvas}
                    className={
                        options.miniViewVisibleHandle.emptyContent
                            ? 'rg-mv-canvas-reset'
                            : ''
                    }
                    onClick={onClickCanvas}
                />
                <div
                    className="rg-mv-visible-area"
                    onMouseDown={onMouseDown}
                    style={{
                        transform: `translate(${options.miniViewVisibleHandle.x}px, ${options.miniViewVisibleHandle.y}px)`,
                        // left: `${options.miniViewVisibleHandle.x}px`,
                        // top: `${options.miniViewVisibleHandle.y}px`,
                        width: options.miniViewVisibleHandle.width + 'px',
                        height: options.miniViewVisibleHandle.height + 'px',
                    }}
                ></div>
            </div>
        </div>
    );
};

export default RGMiniView;
